import type { Category, Item } from "./types";

// Curated bank. `wiki` is the exact Wikipedia article title (URL-encoded by the API client).
// Underscores are fine; the REST API accepts them.
// Every slug has been verified to return >0 pageviews from the Wikimedia API.
export const ITEMS: Item[] = [
  // --- music ---
  { id: "taylor-swift", name: "Taylor Swift", wiki: "Taylor_Swift", category: "music", emoji: "🎤" },
  { id: "the-beatles", name: "The Beatles", wiki: "The_Beatles", category: "music", emoji: "🎸" },
  { id: "drake", name: "Drake", wiki: "Drake_(musician)", category: "music", emoji: "🎤" },
  { id: "billie-eilish", name: "Billie Eilish", wiki: "Billie_Eilish", category: "music", emoji: "🎤" },
  { id: "beyonce", name: "Beyoncé", wiki: "Beyonc%C3%A9", category: "music", emoji: "🎤" },
  { id: "bad-bunny", name: "Bad Bunny", wiki: "Bad_Bunny", category: "music", emoji: "🎤" },
  { id: "bts", name: "BTS", wiki: "BTS", category: "music", emoji: "🎤" },
  { id: "olivia-rodrigo", name: "Olivia Rodrigo", wiki: "Olivia_Rodrigo", category: "music", emoji: "🎤" },
  { id: "harry-styles", name: "Harry Styles", wiki: "Harry_Styles", category: "music", emoji: "🎤" },
  { id: "ed-sheeran", name: "Ed Sheeran", wiki: "Ed_Sheeran", category: "music", emoji: "🎸" },
  { id: "adele", name: "Adele", wiki: "Adele", category: "music", emoji: "🎤" },
  { id: "the-weeknd", name: "The Weeknd", wiki: "The_Weeknd", category: "music", emoji: "🎤" },
  { id: "bob-dylan", name: "Bob Dylan", wiki: "Bob_Dylan", category: "music", emoji: "🎸" },
  { id: "david-bowie", name: "David Bowie", wiki: "David_Bowie", category: "music", emoji: "🎤" },
  { id: "pink-floyd", name: "Pink Floyd", wiki: "Pink_Floyd", category: "music", emoji: "🎸" },
  { id: "nirvana", name: "Nirvana", wiki: "Nirvana_(band)", category: "music", emoji: "🎸" },
  { id: "queen", name: "Queen", wiki: "Queen_(band)", category: "music", emoji: "🎸" },
  { id: "phoebe-bridgers", name: "Phoebe Bridgers", wiki: "Phoebe_Bridgers", category: "music", emoji: "🎤" },
  { id: "mitski", name: "Mitski", wiki: "Mitski", category: "music", emoji: "🎤" },
  { id: "japanese-breakfast", name: "Japanese Breakfast", wiki: "Japanese_Breakfast", category: "music", emoji: "🎤" },
  { id: "alvvays", name: "Alvvays", wiki: "Alvvays", category: "music", emoji: "🎸" },
  { id: "big-thief", name: "Big Thief", wiki: "Big_Thief", category: "music", emoji: "🎸" },
  { id: "bon-iver", name: "Bon Iver", wiki: "Bon_Iver", category: "music", emoji: "🎸" },
  { id: "vampire-weekend", name: "Vampire Weekend", wiki: "Vampire_Weekend", category: "music", emoji: "🎸" },
  { id: "arcade-fire", name: "Arcade Fire", wiki: "Arcade_Fire", category: "music", emoji: "🎸" },
  { id: "radiohead", name: "Radiohead", wiki: "Radiohead", category: "music", emoji: "🎸" },
  { id: "fleetwood-mac", name: "Fleetwood Mac", wiki: "Fleetwood_Mac", category: "music", emoji: "🎸" },
  { id: "kanye-west", name: "Kanye West", wiki: "Kanye_West", category: "music", emoji: "🎤" },
  { id: "frank-ocean", name: "Frank Ocean", wiki: "Frank_Ocean", category: "music", emoji: "🎤" },
  { id: "tyler-the-creator", name: "Tyler, the Creator", wiki: "Tyler,_the_Creator", category: "music", emoji: "🎤" },
  { id: "king-gizzard", name: "King Gizzard & the Lizard Wizard", wiki: "King_Gizzard_%26_the_Lizard_Wizard", category: "music", emoji: "🎸" },
  { id: "weyes-blood", name: "Weyes Blood", wiki: "Weyes_Blood", category: "music", emoji: "🎤" },
  { id: "sufjan-stevens", name: "Sufjan Stevens", wiki: "Sufjan_Stevens", category: "music", emoji: "🎸" },
  { id: "soccer-mommy", name: "Soccer Mommy", wiki: "Soccer_Mommy", category: "music", emoji: "🎸" },
  { id: "snail-mail", name: "Snail Mail", wiki: "Snail_Mail_(musician)", category: "music", emoji: "🎤" },
  { id: "faye-webster", name: "Faye Webster", wiki: "Faye_Webster", category: "music", emoji: "🎤" },
  { id: "black-country-new-road", name: "Black Country, New Road", wiki: "Black_Country,_New_Road", category: "music", emoji: "🎸" },
  { id: "caroline-polachek", name: "Caroline Polachek", wiki: "Caroline_Polachek", category: "music", emoji: "🎤" },
  { id: "cocteau-twins", name: "Cocteau Twins", wiki: "Cocteau_Twins", category: "music", emoji: "🎸" },
  { id: "my-bloody-valentine", name: "My Bloody Valentine", wiki: "My_Bloody_Valentine_(band)", category: "music", emoji: "🎸" },
  { id: "slowdive", name: "Slowdive", wiki: "Slowdive", category: "music", emoji: "🎸" },
  { id: "beach-house", name: "Beach House", wiki: "Beach_House", category: "music", emoji: "🎸" },
  { id: "mac-demarco", name: "Mac DeMarco", wiki: "Mac_DeMarco", category: "music", emoji: "🎸" },
  { id: "tame-impala", name: "Tame Impala", wiki: "Tame_Impala", category: "music", emoji: "🎸" },
  { id: "father-john-misty", name: "Father John Misty", wiki: "Father_John_Misty", category: "music", emoji: "🎸" },
  { id: "st-vincent", name: "St. Vincent", wiki: "St._Vincent_(musician)", category: "music", emoji: "🎸" },
  { id: "daft-punk", name: "Daft Punk", wiki: "Daft_Punk", category: "music", emoji: "🎛️" },
  { id: "aphex-twin", name: "Aphex Twin", wiki: "Aphex_Twin", category: "music", emoji: "🎛️" },
  { id: "boards-of-canada", name: "Boards of Canada", wiki: "Boards_of_Canada", category: "music", emoji: "🎛️" },

  // --- food ---
  { id: "pizza", name: "Pizza", wiki: "Pizza", category: "food", emoji: "🍕" },
  { id: "sushi", name: "Sushi", wiki: "Sushi", category: "food", emoji: "🍣" },
  { id: "ramen", name: "Ramen", wiki: "Ramen", category: "food", emoji: "🍜" },
  { id: "pho", name: "Phở", wiki: "Pho", category: "food", emoji: "🍜" },
  { id: "kimchi", name: "Kimchi", wiki: "Kimchi", category: "food", emoji: "🥬" },
  { id: "natto", name: "Nattō", wiki: "Natt%C5%8D", category: "food", emoji: "🫘" },
  { id: "kombucha", name: "Kombucha", wiki: "Kombucha", category: "food", emoji: "🍵" },
  { id: "avocado-toast", name: "Avocado toast", wiki: "Avocado_toast", category: "food", emoji: "🥑" },
  { id: "burger", name: "Hamburger", wiki: "Hamburger", category: "food", emoji: "🍔" },
  { id: "tacos", name: "Taco", wiki: "Taco", category: "food", emoji: "🌮" },
  { id: "poke", name: "Poke", wiki: "Poke_(dish)", category: "food", emoji: "🐟" },
  { id: "ceviche", name: "Ceviche", wiki: "Ceviche", category: "food", emoji: "🐟" },
  { id: "shakshuka", name: "Shakshouka", wiki: "Shakshouka", category: "food", emoji: "🍳" },
  { id: "miso-soup", name: "Miso soup", wiki: "Miso_soup", category: "food", emoji: "🍜" },
  { id: "kouign-amann", name: "Kouign-amann", wiki: "Kouign-amann", category: "food", emoji: "🥐" },
  { id: "croissant", name: "Croissant", wiki: "Croissant", category: "food", emoji: "🥐" },
  { id: "biryani", name: "Biryani", wiki: "Biryani", category: "food", emoji: "🍛" },
  { id: "butter-chicken", name: "Butter chicken", wiki: "Butter_chicken", category: "food", emoji: "🍛" },
  { id: "dosa", name: "Dosa", wiki: "Dosa", category: "food", emoji: "🥞" },
  { id: "carbonara", name: "Carbonara", wiki: "Carbonara", category: "food", emoji: "🍝" },
  { id: "lasagna", name: "Lasagna", wiki: "Lasagna", category: "food", emoji: "🍝" },
  { id: "risotto", name: "Risotto", wiki: "Risotto", category: "food", emoji: "🍚" },
  { id: "cacio-e-pepe", name: "Cacio e pepe", wiki: "Cacio_e_pepe", category: "food", emoji: "🍝" },
  { id: "mole", name: "Mole", wiki: "Mole_(sauce)", category: "food", emoji: "🌶️" },
  { id: "pupusa", name: "Pupusa", wiki: "Pupusa", category: "food", emoji: "🫓" },
  { id: "arepa", name: "Arepa", wiki: "Arepa", category: "food", emoji: "🫓" },
  { id: "bibimbap", name: "Bibimbap", wiki: "Bibimbap", category: "food", emoji: "🍲" },
  { id: "banh-mi", name: "Bánh mì", wiki: "B%C3%A1nh_m%C3%AC", category: "food", emoji: "🥖" },
  { id: "laksa", name: "Laksa", wiki: "Laksa", category: "food", emoji: "🍜" },
  { id: "pad-thai", name: "Pad thai", wiki: "Pad_thai", category: "food", emoji: "🍜" },
  { id: "dim-sum", name: "Dim sum", wiki: "Dim_sum", category: "food", emoji: "🥟" },
  { id: "takoyaki", name: "Takoyaki", wiki: "Takoyaki", category: "food", emoji: "🐙" },
  { id: "tonkatsu", name: "Tonkatsu", wiki: "Tonkatsu", category: "food", emoji: "🍱" },
  { id: "sourdough", name: "Sourdough", wiki: "Sourdough", category: "food", emoji: "🍞" },
  { id: "tahini", name: "Tahini", wiki: "Tahini", category: "food", emoji: "🥣" },
  { id: "french-fries", name: "French fries", wiki: "French_fries", category: "food", emoji: "🍟" },
  { id: "fried-chicken", name: "Fried chicken", wiki: "Fried_chicken", category: "food", emoji: "🍗" },
  { id: "durian", name: "Durian", wiki: "Durian", category: "food", emoji: "🥥" },

  // --- cities ---
  { id: "new-york", name: "New York City", wiki: "New_York_City", category: "cities", emoji: "🗽" },
  { id: "paris", name: "Paris", wiki: "Paris", category: "cities", emoji: "🗼" },
  { id: "tokyo", name: "Tokyo", wiki: "Tokyo", category: "cities", emoji: "🗾" },
  { id: "london", name: "London", wiki: "London", category: "cities", emoji: "🎡" },
  { id: "berlin", name: "Berlin", wiki: "Berlin", category: "cities", emoji: "🍻" },
  { id: "portland", name: "Portland, Oregon", wiki: "Portland,_Oregon", category: "cities", emoji: "🌲" },
  { id: "austin", name: "Austin, Texas", wiki: "Austin,_Texas", category: "cities", emoji: "🤠" },
  { id: "asheville", name: "Asheville, North Carolina", wiki: "Asheville,_North_Carolina", category: "cities", emoji: "🏔️" },
  { id: "marfa", name: "Marfa, Texas", wiki: "Marfa,_Texas", category: "cities", emoji: "🎨" },
  { id: "reykjavik", name: "Reykjavík", wiki: "Reykjav%C3%ADk", category: "cities", emoji: "❄️" },
  { id: "lisbon", name: "Lisbon", wiki: "Lisbon", category: "cities", emoji: "🌊" },
  { id: "copenhagen", name: "Copenhagen", wiki: "Copenhagen", category: "cities", emoji: "🚲" },
  { id: "tulum", name: "Tulum", wiki: "Tulum", category: "cities", emoji: "🌴" },
  { id: "oaxaca", name: "Oaxaca City", wiki: "Oaxaca_City", category: "cities", emoji: "🌶️" },
  { id: "los-angeles", name: "Los Angeles", wiki: "Los_Angeles", category: "cities", emoji: "🌴" },
  { id: "chicago", name: "Chicago", wiki: "Chicago", category: "cities", emoji: "🏙️" },
  { id: "san-francisco", name: "San Francisco", wiki: "San_Francisco", category: "cities", emoji: "🌉" },
  { id: "miami", name: "Miami", wiki: "Miami", category: "cities", emoji: "🌴" },
  { id: "las-vegas", name: "Las Vegas", wiki: "Las_Vegas", category: "cities", emoji: "🎰" },
  { id: "seattle", name: "Seattle", wiki: "Seattle", category: "cities", emoji: "🏔️" },
  { id: "boston", name: "Boston", wiki: "Boston", category: "cities", emoji: "🦞" },
  { id: "toronto", name: "Toronto", wiki: "Toronto", category: "cities", emoji: "🍁" },
  { id: "mexico-city", name: "Mexico City", wiki: "Mexico_City", category: "cities", emoji: "🌮" },
  { id: "rome", name: "Rome", wiki: "Rome", category: "cities", emoji: "🏛️" },
  { id: "barcelona", name: "Barcelona", wiki: "Barcelona", category: "cities", emoji: "🏖️" },
  { id: "amsterdam", name: "Amsterdam", wiki: "Amsterdam", category: "cities", emoji: "🚲" },
  { id: "bangkok", name: "Bangkok", wiki: "Bangkok", category: "cities", emoji: "🛺" },
  { id: "dubai", name: "Dubai", wiki: "Dubai", category: "cities", emoji: "🏗️" },
  { id: "sydney", name: "Sydney", wiki: "Sydney", category: "cities", emoji: "🦘" },
  { id: "hong-kong", name: "Hong Kong", wiki: "Hong_Kong", category: "cities", emoji: "🏙️" },
  { id: "mumbai", name: "Mumbai", wiki: "Mumbai", category: "cities", emoji: "🇮🇳" },
  { id: "porto", name: "Porto", wiki: "Porto", category: "cities", emoji: "🍷" },
  { id: "cape-town", name: "Cape Town", wiki: "Cape_Town", category: "cities", emoji: "🏔️" },
  { id: "tbilisi", name: "Tbilisi", wiki: "Tbilisi", category: "cities", emoji: "🍷" },
  { id: "tallinn", name: "Tallinn", wiki: "Tallinn", category: "cities", emoji: "🏰" },
  { id: "hanoi", name: "Hanoi", wiki: "Hanoi", category: "cities", emoji: "🥢" },
  { id: "antwerp", name: "Antwerp", wiki: "Antwerp", category: "cities", emoji: "💎" },
  { id: "joshua-tree", name: "Joshua Tree, California", wiki: "Joshua_Tree,_California", category: "cities", emoji: "🌵" },
  { id: "hudson-ny", name: "Hudson, New York", wiki: "Hudson,_New_York", category: "cities", emoji: "🏘️" },
  { id: "provincetown", name: "Provincetown, Massachusetts", wiki: "Provincetown,_Massachusetts", category: "cities", emoji: "🏖️" },

  // --- movies ---
  { id: "titanic", name: "Titanic (1997 film)", wiki: "Titanic_(1997_film)", category: "movies", emoji: "🚢" },
  { id: "avengers-endgame", name: "Avengers: Endgame", wiki: "Avengers:_Endgame", category: "movies", emoji: "🦸" },
  { id: "barbie", name: "Barbie (film)", wiki: "Barbie_(film)", category: "movies", emoji: "👱‍♀️" },
  { id: "oppenheimer", name: "Oppenheimer (film)", wiki: "Oppenheimer_(film)", category: "movies", emoji: "💥" },
  { id: "parasite", name: "Parasite (2019 film)", wiki: "Parasite_(2019_film)", category: "movies", emoji: "🎬" },
  { id: "everything-everywhere", name: "Everything Everywhere All at Once", wiki: "Everything_Everywhere_All_at_Once", category: "movies", emoji: "🥯" },
  { id: "the-lighthouse", name: "The Lighthouse (2019 film)", wiki: "The_Lighthouse_(2019_film)", category: "movies", emoji: "🦞" },
  { id: "midsommar", name: "Midsommar (film)", wiki: "Midsommar_(film)", category: "movies", emoji: "🌼" },
  { id: "moonlight", name: "Moonlight (2016 film)", wiki: "Moonlight_(2016_film)", category: "movies", emoji: "🌙" },
  { id: "the-favourite", name: "The Favourite", wiki: "The_Favourite", category: "movies", emoji: "👑" },
  { id: "frances-ha", name: "Frances Ha", wiki: "Frances_Ha", category: "movies", emoji: "💃" },
  { id: "lady-bird", name: "Lady Bird (film)", wiki: "Lady_Bird_(film)", category: "movies", emoji: "🐦" },
  { id: "inception", name: "Inception", wiki: "Inception", category: "movies", emoji: "🌀" },
  { id: "the-dark-knight", name: "The Dark Knight", wiki: "The_Dark_Knight", category: "movies", emoji: "🦇" },
  { id: "avatar", name: "Avatar (2009 film)", wiki: "Avatar_(2009_film)", category: "movies", emoji: "🌌" },
  { id: "pulp-fiction", name: "Pulp Fiction", wiki: "Pulp_Fiction", category: "movies", emoji: "🔫" },
  { id: "interstellar", name: "Interstellar (film)", wiki: "Interstellar_(film)", category: "movies", emoji: "🪐" },
  { id: "the-godfather", name: "The Godfather", wiki: "The_Godfather", category: "movies", emoji: "🎩" },
  { id: "forrest-gump", name: "Forrest Gump", wiki: "Forrest_Gump", category: "movies", emoji: "🏃" },
  { id: "aftersun", name: "Aftersun", wiki: "Aftersun", category: "movies", emoji: "📼" },
  { id: "past-lives", name: "Past Lives (film)", wiki: "Past_Lives_(film)", category: "movies", emoji: "✨" },
  { id: "uncut-gems", name: "Uncut Gems", wiki: "Uncut_Gems", category: "movies", emoji: "💎" },
  { id: "burning", name: "Burning (2018 film)", wiki: "Burning_(2018_film)", category: "movies", emoji: "🔥" },
  { id: "drive-my-car", name: "Drive My Car (film)", wiki: "Drive_My_Car_(film)", category: "movies", emoji: "🚗" },
  { id: "petite-maman", name: "Petite Maman", wiki: "Petite_Maman", category: "movies", emoji: "👧" },
  { id: "first-cow", name: "First Cow", wiki: "First_Cow", category: "movies", emoji: "🐄" },
  { id: "minari", name: "Minari (film)", wiki: "Minari_(film)", category: "movies", emoji: "🌱" },
  { id: "the-power-of-the-dog", name: "The Power of the Dog (film)", wiki: "The_Power_of_the_Dog_(film)", category: "movies", emoji: "🐕" },
  { id: "nomadland", name: "Nomadland", wiki: "Nomadland", category: "movies", emoji: "🚐" },
  { id: "the-florida-project", name: "The Florida Project", wiki: "The_Florida_Project", category: "movies", emoji: "🏨" },

  // --- tv ---
  { id: "friends", name: "Friends", wiki: "Friends", category: "tv", emoji: "📺" },
  { id: "the-office", name: "The Office (American TV series)", wiki: "The_Office_(American_TV_series)", category: "tv", emoji: "📎" },
  { id: "game-of-thrones", name: "Game of Thrones", wiki: "Game_of_Thrones", category: "tv", emoji: "🐉" },
  { id: "stranger-things", name: "Stranger Things", wiki: "Stranger_Things", category: "tv", emoji: "🔦" },
  { id: "breaking-bad", name: "Breaking Bad", wiki: "Breaking_Bad", category: "tv", emoji: "🧪" },
  { id: "mad-men", name: "Mad Men", wiki: "Mad_Men", category: "tv", emoji: "🥃" },
  { id: "succession", name: "Succession (TV series)", wiki: "Succession_(TV_series)", category: "tv", emoji: "🏛️" },
  { id: "atlanta-tv", name: "Atlanta (TV series)", wiki: "Atlanta_(TV_series)", category: "tv", emoji: "🍑" },
  { id: "severance", name: "Severance (TV series)", wiki: "Severance_(TV_series)", category: "tv", emoji: "🧠" },
  { id: "the-bear", name: "The Bear (TV series)", wiki: "The_Bear_(TV_series)", category: "tv", emoji: "🐻" },
  { id: "fleabag", name: "Fleabag", wiki: "Fleabag", category: "tv", emoji: "🦊" },
  { id: "better-call-saul", name: "Better Call Saul", wiki: "Better_Call_Saul", category: "tv", emoji: "⚖️" },
  { id: "bojack-horseman", name: "BoJack Horseman", wiki: "BoJack_Horseman", category: "tv", emoji: "🐴" },
  { id: "twin-peaks", name: "Twin Peaks", wiki: "Twin_Peaks", category: "tv", emoji: "🌲" },
  { id: "the-sopranos", name: "The Sopranos", wiki: "The_Sopranos", category: "tv", emoji: "🍝" },
  { id: "curb-your-enthusiasm", name: "Curb Your Enthusiasm", wiki: "Curb_Your_Enthusiasm", category: "tv", emoji: "😤" },
  { id: "i-think-you-should-leave", name: "I Think You Should Leave with Tim Robinson", wiki: "I_Think_You_Should_Leave_with_Tim_Robinson", category: "tv", emoji: "🚪" },
  { id: "reservation-dogs", name: "Reservation Dogs", wiki: "Reservation_Dogs", category: "tv", emoji: "🐕" },
  { id: "mr-robot", name: "Mr. Robot", wiki: "Mr._Robot", category: "tv", emoji: "🤖" },
  { id: "yellowjackets", name: "Yellowjackets (TV series)", wiki: "Yellowjackets_(TV_series)", category: "tv", emoji: "🐝" },
  { id: "the-wire", name: "The Wire", wiki: "The_Wire", category: "tv", emoji: "📞" },
  { id: "lost", name: "Lost (TV series)", wiki: "Lost_(TV_series)", category: "tv", emoji: "🏝️" },
  { id: "the-mandalorian", name: "The Mandalorian", wiki: "The_Mandalorian", category: "tv", emoji: "👶" },
  { id: "bluey", name: "Bluey", wiki: "Bluey_(2018_TV_series)", category: "tv", emoji: "🐶" },
  { id: "greys-anatomy", name: "Grey's Anatomy", wiki: "Grey%27s_Anatomy", category: "tv", emoji: "🩺" },
  { id: "the-big-bang-theory", name: "The Big Bang Theory", wiki: "The_Big_Bang_Theory", category: "tv", emoji: "🔬" },
  { id: "how-i-met-your-mother", name: "How I Met Your Mother", wiki: "How_I_Met_Your_Mother", category: "tv", emoji: "🍻" },
  { id: "the-crown", name: "The Crown (TV series)", wiki: "The_Crown_(TV_series)", category: "tv", emoji: "👑" },
  { id: "the-walking-dead", name: "The Walking Dead (TV series)", wiki: "The_Walking_Dead_(TV_series)", category: "tv", emoji: "🧟" },
  { id: "this-is-us", name: "This Is Us", wiki: "This_Is_Us", category: "tv", emoji: "👨‍👩‍👧‍👦" },
  { id: "modern-family", name: "Modern Family", wiki: "Modern_Family", category: "tv", emoji: "🏡" },
  { id: "parks-and-recreation", name: "Parks and Recreation", wiki: "Parks_and_Recreation", category: "tv", emoji: "🌳" },
  { id: "brooklyn-nine-nine", name: "Brooklyn Nine-Nine", wiki: "Brooklyn_Nine-Nine", category: "tv", emoji: "🚓" },
  { id: "the-simpsons", name: "The Simpsons", wiki: "The_Simpsons", category: "tv", emoji: "🍩" },
  { id: "family-guy", name: "Family Guy", wiki: "Family_Guy", category: "tv", emoji: "🐶" },
  { id: "south-park", name: "South Park", wiki: "South_Park", category: "tv", emoji: "⛄" },
  { id: "seinfeld", name: "Seinfeld", wiki: "Seinfeld", category: "tv", emoji: "😂" },
  { id: "frasier", name: "Frasier", wiki: "Frasier", category: "tv", emoji: "🎙️" },
  { id: "house-tv", name: "House (TV series)", wiki: "House_(TV_series)", category: "tv", emoji: "💊" },
  { id: "the-west-wing", name: "The West Wing", wiki: "The_West_Wing", category: "tv", emoji: "🏛️" },
  { id: "twenty-four", name: "24 (TV series)", wiki: "24_(TV_series)", category: "tv", emoji: "⏱️" },
  { id: "desperate-housewives", name: "Desperate Housewives", wiki: "Desperate_Housewives", category: "tv", emoji: "🏘️" },
  { id: "gossip-girl", name: "Gossip Girl", wiki: "Gossip_Girl", category: "tv", emoji: "💋" },
  { id: "supernatural", name: "Supernatural (American TV series)", wiki: "Supernatural_(American_TV_series)", category: "tv", emoji: "👻" },
  { id: "bridgerton", name: "Bridgerton", wiki: "Bridgerton", category: "tv", emoji: "💃" },
  { id: "downton-abbey", name: "Downton Abbey", wiki: "Downton_Abbey", category: "tv", emoji: "🎩" },
  { id: "the-witcher", name: "The Witcher (TV series)", wiki: "The_Witcher_(TV_series)", category: "tv", emoji: "⚔️" },
  { id: "wednesday", name: "Wednesday (TV series)", wiki: "Wednesday_(TV_series)", category: "tv", emoji: "🖤" },
  { id: "squid-game", name: "Squid Game", wiki: "Squid_Game", category: "tv", emoji: "🦑" },
  { id: "cobra-kai", name: "Cobra Kai", wiki: "Cobra_Kai", category: "tv", emoji: "🥋" },
  { id: "orange-is-the-new-black", name: "Orange Is the New Black", wiki: "Orange_Is_the_New_Black", category: "tv", emoji: "🍊" },
  { id: "the-umbrella-academy", name: "The Umbrella Academy (TV series)", wiki: "The_Umbrella_Academy_(TV_series)", category: "tv", emoji: "☂️" },
  { id: "you-tv", name: "You (TV series)", wiki: "You_(TV_series)", category: "tv", emoji: "📚" },
  { id: "dexter", name: "Dexter (TV series)", wiki: "Dexter_(TV_series)", category: "tv", emoji: "🔪" },
  { id: "prison-break", name: "Prison Break", wiki: "Prison_Break", category: "tv", emoji: "⛓️" },
  { id: "ncis", name: "NCIS (TV series)", wiki: "NCIS_(TV_series)", category: "tv", emoji: "🔎" },
  { id: "law-and-order-svu", name: "Law & Order: Special Victims Unit", wiki: "Law_%26_Order:_Special_Victims_Unit", category: "tv", emoji: "🚨" },
  { id: "csi", name: "CSI: Crime Scene Investigation", wiki: "CSI:_Crime_Scene_Investigation", category: "tv", emoji: "🔬" },
  { id: "the-x-files", name: "The X-Files", wiki: "The_X-Files", category: "tv", emoji: "🛸" },
  { id: "suits", name: "Suits (American TV series)", wiki: "Suits_(American_TV_series)", category: "tv", emoji: "👔" },
  { id: "survivor", name: "Survivor (American TV series)", wiki: "Survivor_(American_TV_series)", category: "tv", emoji: "🏝️" },
  { id: "the-amazing-race", name: "The Amazing Race", wiki: "The_Amazing_Race", category: "tv", emoji: "🌍" },
  { id: "american-idol", name: "American Idol", wiki: "American_Idol", category: "tv", emoji: "🎙️" },
  { id: "the-voice", name: "The Voice (American TV series)", wiki: "The_Voice_(American_TV_series)", category: "tv", emoji: "🎶" },
  { id: "rupauls-drag-race", name: "RuPaul's Drag Race", wiki: "RuPaul%27s_Drag_Race", category: "tv", emoji: "👑" },
  { id: "the-bachelor", name: "The Bachelor (American TV series)", wiki: "The_Bachelor_(American_TV_series)", category: "tv", emoji: "🌹" },
  { id: "jeopardy", name: "Jeopardy!", wiki: "Jeopardy!", category: "tv", emoji: "❓" },
  { id: "wheel-of-fortune", name: "Wheel of Fortune (American game show)", wiki: "Wheel_of_Fortune_(American_game_show)", category: "tv", emoji: "🎡" },
  { id: "saturday-night-live", name: "Saturday Night Live", wiki: "Saturday_Night_Live", category: "tv", emoji: "🎭" },
  { id: "the-daily-show", name: "The Daily Show", wiki: "The_Daily_Show", category: "tv", emoji: "📰" },
  { id: "the-tonight-show-fallon", name: "The Tonight Show Starring Jimmy Fallon", wiki: "The_Tonight_Show_Starring_Jimmy_Fallon", category: "tv", emoji: "🎤" },
  { id: "spongebob-squarepants", name: "SpongeBob SquarePants", wiki: "SpongeBob_SquarePants", category: "tv", emoji: "🧽" },
  { id: "avatar-the-last-airbender", name: "Avatar: The Last Airbender", wiki: "Avatar:_The_Last_Airbender", category: "tv", emoji: "🌬️" },
  { id: "rick-and-morty", name: "Rick and Morty", wiki: "Rick_and_Morty", category: "tv", emoji: "🛸" },
  { id: "pokemon-tv", name: "Pokémon (TV series)", wiki: "Pok%C3%A9mon_(TV_series)", category: "tv", emoji: "⚡" },
  { id: "wandavision", name: "WandaVision", wiki: "WandaVision", category: "tv", emoji: "📺" },
  { id: "the-boys", name: "The Boys (TV series)", wiki: "The_Boys_(TV_series)", category: "tv", emoji: "🦹" },
  { id: "the-handmaids-tale", name: "The Handmaid's Tale (TV series)", wiki: "The_Handmaid%27s_Tale_(TV_series)", category: "tv", emoji: "🔴" },
  { id: "westworld", name: "Westworld (TV series)", wiki: "Westworld_(TV_series)", category: "tv", emoji: "🤠" },
  { id: "black-mirror", name: "Black Mirror", wiki: "Black_Mirror", category: "tv", emoji: "📱" },
  { id: "the-white-lotus", name: "The White Lotus", wiki: "The_White_Lotus", category: "tv", emoji: "🏝️" },
  { id: "fargo", name: "Fargo (TV series)", wiki: "Fargo_(TV_series)", category: "tv", emoji: "❄️" },
  { id: "true-detective", name: "True Detective", wiki: "True_Detective", category: "tv", emoji: "🚬" },
  { id: "euphoria", name: "Euphoria (American TV series)", wiki: "Euphoria_(American_TV_series)", category: "tv", emoji: "💜" },
  { id: "watchmen", name: "Watchmen (TV series)", wiki: "Watchmen_(TV_series)", category: "tv", emoji: "🎭" },
  { id: "chernobyl", name: "Chernobyl (miniseries)", wiki: "Chernobyl_(miniseries)", category: "tv", emoji: "☢️" },
  { id: "mindhunter", name: "Mindhunter (TV series)", wiki: "Mindhunter_(TV_series)", category: "tv", emoji: "🔍" },
  { id: "dark", name: "Dark (TV series)", wiki: "Dark_(TV_series)", category: "tv", emoji: "🕳️" },
  { id: "barry", name: "Barry (TV series)", wiki: "Barry_(TV_series)", category: "tv", emoji: "🎬" },
  { id: "deadwood", name: "Deadwood (TV series)", wiki: "Deadwood_(TV_series)", category: "tv", emoji: "🤠" },
  { id: "boardwalk-empire", name: "Boardwalk Empire", wiki: "Boardwalk_Empire", category: "tv", emoji: "🎩" },
  { id: "six-feet-under", name: "Six Feet Under (TV series)", wiki: "Six_Feet_Under_(TV_series)", category: "tv", emoji: "⚰️" },
  { id: "the-americans", name: "The Americans", wiki: "The_Americans", category: "tv", emoji: "🕴️" },
  { id: "the-leftovers", name: "The Leftovers (TV series)", wiki: "The_Leftovers_(TV_series)", category: "tv", emoji: "🌅" },
  { id: "hannibal", name: "Hannibal (TV series)", wiki: "Hannibal_(TV_series)", category: "tv", emoji: "🍷" },
  { id: "mare-of-easttown", name: "Mare of Easttown", wiki: "Mare_of_Easttown", category: "tv", emoji: "🚬" },
  { id: "the-night-of", name: "The Night Of", wiki: "The_Night_Of", category: "tv", emoji: "🌃" },
  { id: "sharp-objects", name: "Sharp Objects (miniseries)", wiki: "Sharp_Objects_(miniseries)", category: "tv", emoji: "🔪" },
  { id: "normal-people-tv", name: "Normal People (TV series)", wiki: "Normal_People_(TV_series)", category: "tv", emoji: "💔" },
  { id: "i-may-destroy-you", name: "I May Destroy You", wiki: "I_May_Destroy_You", category: "tv", emoji: "🩹" },
  { id: "beef", name: "Beef (TV series)", wiki: "Beef_(TV_series)", category: "tv", emoji: "🚗" },
  { id: "the-jinx", name: "The Jinx (TV series)", wiki: "The_Jinx_(TV_series)", category: "tv", emoji: "🎙️" },
  { id: "wild-wild-country", name: "Wild Wild Country", wiki: "Wild_Wild_Country", category: "tv", emoji: "🧘" },
  { id: "babylon-berlin", name: "Babylon Berlin", wiki: "Babylon_Berlin", category: "tv", emoji: "🎷" },
  { id: "station-eleven", name: "Station Eleven (miniseries)", wiki: "Station_Eleven_(miniseries)", category: "tv", emoji: "🎻" },
  { id: "the-knick", name: "The Knick", wiki: "The_Knick", category: "tv", emoji: "🏥" },
  { id: "nathan-for-you", name: "Nathan for You", wiki: "Nathan_for_You", category: "tv", emoji: "🧥" },
  { id: "the-rehearsal", name: "The Rehearsal (TV series)", wiki: "The_Rehearsal_(TV_series)", category: "tv", emoji: "🎭" },
  { id: "how-to-with-john-wilson", name: "How To with John Wilson", wiki: "How_To_with_John_Wilson", category: "tv", emoji: "📷" },
  { id: "russian-doll", name: "Russian Doll (TV series)", wiki: "Russian_Doll_(TV_series)", category: "tv", emoji: "🪆" },
  { id: "its-always-sunny-in-philadelphia", name: "It's Always Sunny in Philadelphia", wiki: "It%27s_Always_Sunny_in_Philadelphia", category: "tv", emoji: "🍺" },
  { id: "neon-genesis-evangelion", name: "Neon Genesis Evangelion", wiki: "Neon_Genesis_Evangelion", category: "tv", emoji: "🤖" },
  { id: "cowboy-bebop", name: "Cowboy Bebop", wiki: "Cowboy_Bebop", category: "tv", emoji: "🚀" },
  { id: "death-note", name: "Death Note (2006 TV series)", wiki: "Death_Note_(2006_TV_series)", category: "tv", emoji: "📓" },
  { id: "mob-psycho-100", name: "Mob Psycho 100", wiki: "Mob_Psycho_100", category: "tv", emoji: "💢" },
  { id: "peep-show", name: "Peep Show (British TV series)", wiki: "Peep_Show_(British_TV_series)", category: "tv", emoji: "👀" },
  { id: "rectify", name: "Rectify", wiki: "Rectify", category: "tv", emoji: "🌾" },
  { id: "halt-and-catch-fire", name: "Halt and Catch Fire (TV series)", wiki: "Halt_and_Catch_Fire_(TV_series)", category: "tv", emoji: "💾" },
  { id: "search-party", name: "Search Party (TV series)", wiki: "Search_Party_(TV_series)", category: "tv", emoji: "🕵️" },
  { id: "party-down", name: "Party Down", wiki: "Party_Down", category: "tv", emoji: "🍸" },
  { id: "los-espookys", name: "Los Espookys", wiki: "Los_Espookys", category: "tv", emoji: "👻" },
  { id: "documentary-now", name: "Documentary Now!", wiki: "Documentary_Now!", category: "tv", emoji: "🎥" },
  { id: "joe-pera-talks-with-you", name: "Joe Pera Talks with You", wiki: "Joe_Pera_Talks_with_You", category: "tv", emoji: "🌙" },
  { id: "garth-marenghis-darkplace", name: "Garth Marenghi's Darkplace", wiki: "Garth_Marenghi%27s_Darkplace", category: "tv", emoji: "🏥" },
  { id: "inside-no-9", name: "Inside No. 9", wiki: "Inside_No._9", category: "tv", emoji: "9️⃣" },
  { id: "the-mighty-boosh", name: "The Mighty Boosh", wiki: "The_Mighty_Boosh", category: "tv", emoji: "🎪" },
  { id: "serial-experiments-lain", name: "Serial Experiments Lain", wiki: "Serial_Experiments_Lain", category: "tv", emoji: "🖥️" },
  { id: "samurai-champloo", name: "Samurai Champloo", wiki: "Samurai_Champloo", category: "tv", emoji: "⚔️" },
  { id: "the-venture-bros", name: "The Venture Bros.", wiki: "The_Venture_Bros.", category: "tv", emoji: "🧪" },
  { id: "the-boondocks", name: "The Boondocks (TV series)", wiki: "The_Boondocks_(TV_series)", category: "tv", emoji: "✊" },
  { id: "smiling-friends", name: "Smiling Friends", wiki: "Smiling_Friends", category: "tv", emoji: "🙂" },
  { id: "the-killing-danish", name: "The Killing (Danish TV series)", wiki: "The_Killing_(Danish_TV_series)", category: "tv", emoji: "🧶" },
  { id: "gomorrah", name: "Gomorrah (TV series)", wiki: "Gomorrah_(TV_series)", category: "tv", emoji: "🔫" },
  { id: "my-brilliant-friend-tv", name: "My Brilliant Friend (TV series)", wiki: "My_Brilliant_Friend_(TV_series)", category: "tv", emoji: "📚" },
  { id: "giri-haji", name: "Giri/Haji", wiki: "Giri%2FHaji", category: "tv", emoji: "🗡️" },
  { id: "devs", name: "Devs (TV series)", wiki: "Devs_(TV_series)", category: "tv", emoji: "🔮" },
  { id: "ramy", name: "Ramy (TV series)", wiki: "Ramy_(TV_series)", category: "tv", emoji: "🕌" },

  // --- books ---
  { id: "harry-potter", name: "Harry Potter", wiki: "Harry_Potter", category: "books", emoji: "⚡" },
  { id: "the-great-gatsby", name: "The Great Gatsby", wiki: "The_Great_Gatsby", category: "books", emoji: "🥂" },
  { id: "1984-book", name: "Nineteen Eighty-Four", wiki: "Nineteen_Eighty-Four", category: "books", emoji: "👁️" },
  { id: "lotr", name: "The Lord of the Rings", wiki: "The_Lord_of_the_Rings", category: "books", emoji: "💍" },
  { id: "to-kill-a-mockingbird", name: "To Kill a Mockingbird", wiki: "To_Kill_a_Mockingbird", category: "books", emoji: "🐦" },
  { id: "the-hunger-games", name: "The Hunger Games", wiki: "The_Hunger_Games", category: "books", emoji: "🏹" },
  { id: "the-catcher-in-the-rye", name: "The Catcher in the Rye", wiki: "The_Catcher_in_the_Rye", category: "books", emoji: "🧢" },
  { id: "pride-and-prejudice", name: "Pride and Prejudice", wiki: "Pride_and_Prejudice", category: "books", emoji: "💌" },
  { id: "infinite-jest", name: "Infinite Jest", wiki: "Infinite_Jest", category: "books", emoji: "🎾" },
  { id: "normal-people", name: "Normal People (novel)", wiki: "Normal_People", category: "books", emoji: "💔" },
  { id: "my-year-of-rest", name: "My Year of Rest and Relaxation", wiki: "My_Year_of_Rest_and_Relaxation", category: "books", emoji: "💊" },
  { id: "just-kids", name: "Just Kids", wiki: "Just_Kids", category: "books", emoji: "📷" },
  { id: "crying-in-h-mart", name: "Crying in H Mart", wiki: "Crying_in_H_Mart", category: "books", emoji: "😢" },
  { id: "pachinko", name: "Pachinko (novel)", wiki: "Pachinko_(novel)", category: "books", emoji: "🎰" },
  { id: "the-secret-history", name: "The Secret History", wiki: "The_Secret_History", category: "books", emoji: "🏛️" },
  { id: "tomorrow-tomorrow", name: "Tomorrow, and Tomorrow, and Tomorrow (novel)", wiki: "Tomorrow,_and_Tomorrow,_and_Tomorrow_(novel)", category: "books", emoji: "🎮" },
  { id: "beloved", name: "Beloved (novel)", wiki: "Beloved_(novel)", category: "books", emoji: "📖" },
  { id: "the-road", name: "The Road", wiki: "The_Road", category: "books", emoji: "🛣️" },
  { id: "lincoln-in-the-bardo", name: "Lincoln in the Bardo", wiki: "Lincoln_in_the_Bardo", category: "books", emoji: "🎩" },
  { id: "a-little-life", name: "A Little Life", wiki: "A_Little_Life", category: "books", emoji: "💔" },
  { id: "atomic-habits", name: "Atomic Habits", wiki: "Atomic_Habits", category: "books", emoji: "⚛️" },
  { id: "sapiens", name: "Sapiens: A Brief History of Humankind", wiki: "Sapiens:_A_Brief_History_of_Humankind", category: "books", emoji: "🧠" },
  { id: "the-alchemist", name: "The Alchemist", wiki: "The_Alchemist_(novel)", category: "books", emoji: "🪄" },
  { id: "where-the-crawdads-sing", name: "Where the Crawdads Sing", wiki: "Where_the_Crawdads_Sing", category: "books", emoji: "🦞" },
  { id: "the-da-vinci-code", name: "The Da Vinci Code", wiki: "The_Da_Vinci_Code", category: "books", emoji: "🔍" },
  { id: "angels-and-demons", name: "Angels & Demons", wiki: "Angels_%26_Demons", category: "books", emoji: "⚛️" },
  { id: "gone-girl", name: "Gone Girl", wiki: "Gone_Girl", category: "books", emoji: "🔪" },
  { id: "the-kite-runner", name: "The Kite Runner", wiki: "The_Kite_Runner", category: "books", emoji: "🪁" },
  { id: "life-of-pi", name: "Life of Pi", wiki: "Life_of_Pi", category: "books", emoji: "🐅" },
  { id: "twilight-book", name: "Twilight (Meyer novel)", wiki: "Twilight_(Meyer_novel)", category: "books", emoji: "🧛" },
  { id: "the-fault-in-our-stars", name: "The Fault in Our Stars", wiki: "The_Fault_in_Our_Stars", category: "books", emoji: "💫" },
  { id: "the-maze-runner", name: "The Maze Runner", wiki: "The_Maze_Runner", category: "books", emoji: "🏃" },
  { id: "divergent-book", name: "Divergent (novel)", wiki: "Divergent_(novel)", category: "books", emoji: "🔥" },
  { id: "the-lightning-thief", name: "Percy Jackson & the Olympians: The Lightning Thief", wiki: "Percy_Jackson_%26_the_Olympians:_The_Lightning_Thief", category: "books", emoji: "⚡" },
  { id: "the-hobbit", name: "The Hobbit", wiki: "The_Hobbit", category: "books", emoji: "🧙" },
  { id: "a-game-of-thrones", name: "A Game of Thrones", wiki: "A_Game_of_Thrones", category: "books", emoji: "🐺" },
  { id: "the-lion-the-witch-and-the-wardrobe", name: "The Lion, the Witch and the Wardrobe", wiki: "The_Lion,_the_Witch_and_the_Wardrobe", category: "books", emoji: "🦁" },
  { id: "charlottes-web", name: "Charlotte's Web", wiki: "Charlotte's_Web", category: "books", emoji: "🕷️" },
  { id: "the-giver", name: "The Giver", wiki: "The_Giver", category: "books", emoji: "🍎" },
  { id: "holes-book", name: "Holes (novel)", wiki: "Holes_(novel)", category: "books", emoji: "🕳️" },
  { id: "where-the-wild-things-are", name: "Where the Wild Things Are", wiki: "Where_the_Wild_Things_Are", category: "books", emoji: "👹" },
  { id: "the-very-hungry-caterpillar", name: "The Very Hungry Caterpillar", wiki: "The_Very_Hungry_Caterpillar", category: "books", emoji: "🐛" },
  { id: "matilda-book", name: "Matilda (novel)", wiki: "Matilda_(novel)", category: "books", emoji: "📚" },
  { id: "charlie-and-the-chocolate-factory", name: "Charlie and the Chocolate Factory", wiki: "Charlie_and_the_Chocolate_Factory", category: "books", emoji: "🍫" },
  { id: "the-hate-u-give", name: "The Hate U Give", wiki: "The_Hate_U_Give", category: "books", emoji: "✊" },
  { id: "it-book", name: "It (novel)", wiki: "It_(novel)", category: "books", emoji: "🤡" },
  { id: "the-shining-book", name: "The Shining (novel)", wiki: "The_Shining_(novel)", category: "books", emoji: "🏨" },
  { id: "the-stand", name: "The Stand", wiki: "The_Stand", category: "books", emoji: "🦠" },
  { id: "the-firm-book", name: "The Firm (novel)", wiki: "The_Firm_(novel)", category: "books", emoji: "⚖️" },
  { id: "a-time-to-kill-book", name: "A Time to Kill (Grisham novel)", wiki: "A_Time_to_Kill_(Grisham_novel)", category: "books", emoji: "👨‍⚖️" },
  { id: "and-then-there-were-none", name: "And Then There Were None", wiki: "And_Then_There_Were_None", category: "books", emoji: "🏝️" },
  { id: "murder-on-the-orient-express", name: "Murder on the Orient Express", wiki: "Murder_on_the_Orient_Express", category: "books", emoji: "🚂" },
  { id: "the-notebook-book", name: "The Notebook (novel)", wiki: "The_Notebook_(novel)", category: "books", emoji: "📓" },
  { id: "it-ends-with-us", name: "It Ends with Us", wiki: "It_Ends_with_Us", category: "books", emoji: "🌸" },
  { id: "fifty-shades-of-grey", name: "Fifty Shades of Grey", wiki: "Fifty_Shades_of_Grey", category: "books", emoji: "⛓️" },
  { id: "outlander-book", name: "Outlander (novel)", wiki: "Outlander_(novel)", category: "books", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "the-lovely-bones", name: "The Lovely Bones", wiki: "The_Lovely_Bones", category: "books", emoji: "👼" },
  { id: "the-time-travelers-wife", name: "The Time Traveler's Wife", wiki: "The_Time_Traveler's_Wife", category: "books", emoji: "⏳" },
  { id: "bridget-joness-diary", name: "Bridget Jones's Diary", wiki: "Bridget_Jones's_Diary", category: "books", emoji: "🍷" },
  { id: "eat-pray-love", name: "Eat, Pray, Love", wiki: "Eat,_Pray,_Love", category: "books", emoji: "🧘" },
  { id: "the-7-habits-of-highly-effective-people", name: "The 7 Habits of Highly Effective People", wiki: "The_7_Habits_of_Highly_Effective_People", category: "books", emoji: "✅" },
  { id: "rich-dad-poor-dad", name: "Rich Dad Poor Dad", wiki: "Rich_Dad_Poor_Dad", category: "books", emoji: "💰" },
  { id: "how-to-win-friends-and-influence-people", name: "How to Win Friends and Influence People", wiki: "How_to_Win_Friends_and_Influence_People", category: "books", emoji: "🤝" },
  { id: "the-subtle-art-of-not-giving-a-fuck", name: "The Subtle Art of Not Giving a Fuck", wiki: "The_Subtle_Art_of_Not_Giving_a_Fuck", category: "books", emoji: "🤷" },
  { id: "educated-memoir", name: "Educated (memoir)", wiki: "Educated_(memoir)", category: "books", emoji: "🎓" },
  { id: "becoming-book", name: "Becoming (book)", wiki: "Becoming_(book)", category: "books", emoji: "👑" },
  { id: "thinking-fast-and-slow", name: "Thinking, Fast and Slow", wiki: "Thinking,_Fast_and_Slow", category: "books", emoji: "⚡" },
  { id: "a-brief-history-of-time", name: "A Brief History of Time", wiki: "A_Brief_History_of_Time", category: "books", emoji: "🌌" },
  { id: "of-mice-and-men", name: "Of Mice and Men", wiki: "Of_Mice_and_Men", category: "books", emoji: "🐭" },
  { id: "the-grapes-of-wrath", name: "The Grapes of Wrath", wiki: "The_Grapes_of_Wrath", category: "books", emoji: "🍇" },
  { id: "lord-of-the-flies", name: "Lord of the Flies", wiki: "Lord_of_the_Flies", category: "books", emoji: "🐚" },
  { id: "animal-farm", name: "Animal Farm", wiki: "Animal_Farm", category: "books", emoji: "🐖" },
  { id: "fahrenheit-451", name: "Fahrenheit 451", wiki: "Fahrenheit_451", category: "books", emoji: "🔥" },
  { id: "adventures-of-huckleberry-finn", name: "Adventures of Huckleberry Finn", wiki: "Adventures_of_Huckleberry_Finn", category: "books", emoji: "🛶" },
  { id: "little-women", name: "Little Women", wiki: "Little_Women", category: "books", emoji: "👧" },
  { id: "jane-eyre", name: "Jane Eyre", wiki: "Jane_Eyre", category: "books", emoji: "🕯️" },
  { id: "slaughterhouse-five", name: "Slaughterhouse-Five", wiki: "Slaughterhouse-Five", category: "books", emoji: "🛸" },
  { id: "the-girl-on-the-train-book", name: "The Girl on the Train (novel)", wiki: "The_Girl_on_the_Train_(novel)", category: "books", emoji: "🚆" },
  { id: "the-help-book", name: "The Help", wiki: "The_Help", category: "books", emoji: "🧹" },
  { id: "diary-of-a-wimpy-kid-book", name: "Diary of a Wimpy Kid (book)", wiki: "Diary_of_a_Wimpy_Kid_(book)", category: "books", emoji: "📔" },
  { id: "the-wind-up-bird-chronicle", name: "The Wind-Up Bird Chronicle", wiki: "The_Wind-Up_Bird_Chronicle", category: "books", emoji: "🐦" },
  { id: "2666", name: "2666", wiki: "2666", category: "books", emoji: "🌃" },
  { id: "my-brilliant-friend", name: "My Brilliant Friend", wiki: "My_Brilliant_Friend", category: "books", emoji: "👭" },
  { id: "the-vegetarian", name: "The Vegetarian", wiki: "The_Vegetarian", category: "books", emoji: "🥦" },
  { id: "flights-novel", name: "Flights (novel)", wiki: "Flights_(novel)", category: "books", emoji: "✈️" },
  { id: "drive-your-plow", name: "Drive Your Plow Over the Bones of the Dead", wiki: "Drive_Your_Plow_Over_the_Bones_of_the_Dead", category: "books", emoji: "🦌" },
  { id: "the-savage-detectives", name: "The Savage Detectives", wiki: "The_Savage_Detectives", category: "books", emoji: "🕵️" },
  { id: "my-struggle-knausgard", name: "My Struggle (Knausgård novels)", wiki: "My_Struggle_(Knausg%C3%A5rd_novels)", category: "books", emoji: "📔" },
  { id: "the-rings-of-saturn", name: "The Rings of Saturn", wiki: "The_Rings_of_Saturn", category: "books", emoji: "🪐" },
  { id: "austerlitz", name: "Austerlitz (novel)", wiki: "Austerlitz_(novel)", category: "books", emoji: "🚉" },
  { id: "the-loser-bernhard", name: "The Loser", wiki: "The_Loser", category: "books", emoji: "🎹" },
  { id: "kafka-on-the-shore", name: "Kafka on the Shore", wiki: "Kafka_on_the_Shore", category: "books", emoji: "🐈" },
  { id: "cursed-bunny", name: "Cursed Bunny", wiki: "Cursed_Bunny", category: "books", emoji: "🐰" },
  { id: "breasts-and-eggs", name: "Breasts and Eggs", wiki: "Breasts_and_Eggs", category: "books", emoji: "🥚" },
  { id: "the-memory-police", name: "The Memory Police", wiki: "The_Memory_Police", category: "books", emoji: "🕵️‍♀️" },
  { id: "convenience-store-woman", name: "Convenience Store Woman", wiki: "Convenience_Store_Woman", category: "books", emoji: "🏪" },
  { id: "mrs-dalloway", name: "Mrs Dalloway", wiki: "Mrs_Dalloway", category: "books", emoji: "🌷" },
  { id: "gravitys-rainbow", name: "Gravity's Rainbow", wiki: "Gravity%27s_Rainbow", category: "books", emoji: "🚀" },
  { id: "the-crying-of-lot-49", name: "The Crying of Lot 49", wiki: "The_Crying_of_Lot_49", category: "books", emoji: "📯" },
  { id: "underworld-delillo", name: "Underworld (novel)", wiki: "Underworld_(novel)", category: "books", emoji: "⚾" },
  { id: "if-on-a-winters-night", name: "If on a winter's night a traveler", wiki: "If_on_a_winter%27s_night_a_traveler", category: "books", emoji: "❄️" },
  { id: "invisible-cities", name: "Invisible Cities", wiki: "Invisible_Cities", category: "books", emoji: "🏙️" },
  { id: "ficciones", name: "Ficciones", wiki: "Ficciones", category: "books", emoji: "🔮" },
  { id: "labyrinths-borges", name: "Labyrinths (short story collection)", wiki: "Labyrinths_(short_story_collection)", category: "books", emoji: "🌀" },
  { id: "pale-fire", name: "Pale Fire", wiki: "Pale_Fire", category: "books", emoji: "🔥" },
  { id: "the-idiot-batuman", name: "The Idiot (Batuman novel)", wiki: "The_Idiot_(Batuman_novel)", category: "books", emoji: "📧" },
  { id: "bunny-novel", name: "Bunny (novel)", wiki: "Bunny_(novel)", category: "books", emoji: "🐇" },
  { id: "severance-ma", name: "Severance (novel)", wiki: "Severance_(novel)", category: "books", emoji: "🦠" },
  { id: "outline-cusk", name: "Outline (novel)", wiki: "Outline_(novel)", category: "books", emoji: "✏️" },
  { id: "10-04-lerner", name: "10:04", wiki: "10:04", category: "books", emoji: "🕙" },
  { id: "a-brief-history-of-seven-killings", name: "A Brief History of Seven Killings", wiki: "A_Brief_History_of_Seven_Killings", category: "books", emoji: "🔫" },
  { id: "milkman-novel", name: "Milkman (novel)", wiki: "Milkman_(novel)", category: "books", emoji: "🥛" },
  { id: "shuggie-bain", name: "Shuggie Bain", wiki: "Shuggie_Bain", category: "books", emoji: "🏚️" },
  { id: "a-tale-for-the-time-being", name: "A Tale for the Time Being", wiki: "A_Tale_for_the_Time_Being", category: "books", emoji: "⏳" },
  { id: "there-there-orange", name: "There There (novel)", wiki: "There_There_(novel)", category: "books", emoji: "🥁" },
  { id: "a-heartbreaking-work", name: "A Heartbreaking Work of Staggering Genius", wiki: "A_Heartbreaking_Work_of_Staggering_Genius", category: "books", emoji: "💔" },
  { id: "jesus-son", name: "Jesus' Son (short story collection)", wiki: "Jesus%27_Son_(short_story_collection)", category: "books", emoji: "💉" },
  { id: "the-hour-of-the-star", name: "The Hour of the Star", wiki: "The_Hour_of_the_Star", category: "books", emoji: "⭐" },
  { id: "pedro-paramo", name: "Pedro Páramo", wiki: "Pedro_P%C3%A1ramo", category: "books", emoji: "💀" },
  { id: "hunger-hamsun", name: "Hunger (Hamsun novel)", wiki: "Hunger_(Hamsun_novel)", category: "books", emoji: "🍞" },
  { id: "zenos-conscience", name: "Zeno's Conscience", wiki: "Zeno%27s_Conscience", category: "books", emoji: "🚬" },
  { id: "the-tin-drum", name: "The Tin Drum", wiki: "The_Tin_Drum", category: "books", emoji: "🥁" },
  { id: "my-name-is-red", name: "My Name Is Red", wiki: "My_Name_Is_Red", category: "books", emoji: "🎨" },
  { id: "the-door-szabo", name: "The Door (Szabó novel)", wiki: "The_Door_(Szab%C3%B3_novel)", category: "books", emoji: "🚪" },
  { id: "the-lover-duras", name: "The Lover (Duras novel)", wiki: "The_Lover_(Duras_novel)", category: "books", emoji: "💋" },
  { id: "the-years-ernaux", name: "The Years (Ernaux book)", wiki: "The_Years_(Ernaux_book)", category: "books", emoji: "📆" },
  { id: "tenth-of-december", name: "Tenth of December: Stories", wiki: "Tenth_of_December:_Stories", category: "books", emoji: "🌨️" },
  { id: "citizen-an-american-lyric", name: "Citizen: An American Lyric", wiki: "Citizen:_An_American_Lyric", category: "books", emoji: "✊" },
  { id: "autobiography-of-red", name: "Autobiography of Red", wiki: "Autobiography_of_Red", category: "books", emoji: "🌋" },
  { id: "ariel-plath", name: "Ariel (poetry collection)", wiki: "Ariel_(poetry_collection)", category: "books", emoji: "🐝" },
  { id: "crush-siken", name: "Crush (Richard Siken)", wiki: "Crush_(Richard_Siken)", category: "books", emoji: "💘" },
  { id: "bluets-nelson", name: "Bluets (poetry collection)", wiki: "Bluets_(poetry_collection)", category: "books", emoji: "💙" },
  { id: "the-argonauts", name: "The Argonauts", wiki: "The_Argonauts", category: "books", emoji: "⛵" },
  { id: "the-periodic-table-levi", name: "The Periodic Table (short story collection)", wiki: "The_Periodic_Table_(short_story_collection)", category: "books", emoji: "⚗️" },
  { id: "trout-fishing-in-america", name: "Trout Fishing in America", wiki: "Trout_Fishing_in_America", category: "books", emoji: "🎣" },
  { id: "ducks-newburyport", name: "Ducks, Newburyport", wiki: "Ducks,_Newburyport", category: "books", emoji: "🦆" },
  { id: "the-temple-of-the-golden-pavilion", name: "The Temple of the Golden Pavilion", wiki: "The_Temple_of_the_Golden_Pavilion", category: "books", emoji: "⛩️" },

  // --- drinks ---
  { id: "coffee", name: "Coffee", wiki: "Coffee", category: "drinks", emoji: "☕" },
  { id: "espresso", name: "Espresso", wiki: "Espresso", category: "drinks", emoji: "☕" },
  { id: "matcha", name: "Matcha", wiki: "Matcha", category: "drinks", emoji: "🍵" },
  { id: "yerba-mate", name: "Yerba mate", wiki: "Yerba_mate", category: "drinks", emoji: "🧉" },
  { id: "natural-wine", name: "Natural wine", wiki: "Natural_wine", category: "drinks", emoji: "🍷" },
  { id: "negroni", name: "Negroni", wiki: "Negroni", category: "drinks", emoji: "🍸" },
  { id: "aperol-spritz", name: "Aperol Spritz", wiki: "Spritz_Veneziano", category: "drinks", emoji: "🥂" },
  { id: "ipa", name: "India pale ale", wiki: "India_pale_ale", category: "drinks", emoji: "🍺" },
  { id: "mezcal", name: "Mezcal", wiki: "Mezcal", category: "drinks", emoji: "🌵" },
  { id: "soju", name: "Soju", wiki: "Soju", category: "drinks", emoji: "🍶" },
  { id: "coca-cola", name: "Coca-Cola", wiki: "Coca-Cola", category: "drinks", emoji: "🥤" },
  { id: "beer", name: "Beer", wiki: "Beer", category: "drinks", emoji: "🍺" },
  { id: "wine", name: "Wine", wiki: "Wine", category: "drinks", emoji: "🍷" },
  { id: "tea", name: "Tea", wiki: "Tea", category: "drinks", emoji: "🍵" },
  { id: "old-fashioned", name: "Old Fashioned", wiki: "Old_fashioned_(cocktail)", category: "drinks", emoji: "🥃" },
  { id: "martini", name: "Martini", wiki: "Martini_(cocktail)", category: "drinks", emoji: "🍸" },
  { id: "margarita", name: "Margarita", wiki: "Margarita", category: "drinks", emoji: "🍹" },
  { id: "cortado", name: "Cortado", wiki: "Cortado", category: "drinks", emoji: "☕" },
  { id: "flat-white", name: "Flat white", wiki: "Flat_white", category: "drinks", emoji: "☕" },
  { id: "sake", name: "Sake", wiki: "Sake", category: "drinks", emoji: "🍶" },
  { id: "chartreuse", name: "Chartreuse", wiki: "Chartreuse_(liqueur)", category: "drinks", emoji: "💚" },
  { id: "fernet-branca", name: "Fernet-Branca", wiki: "Fernet-Branca", category: "drinks", emoji: "🥃" },
  { id: "amaro", name: "Amaro", wiki: "Amaro_(liqueur)", category: "drinks", emoji: "🥃" },
  { id: "pisco", name: "Pisco", wiki: "Pisco", category: "drinks", emoji: "🇵🇪" },

  // --- brands ---
  { id: "starbucks", name: "Starbucks", wiki: "Starbucks", category: "brands", emoji: "☕" },
  { id: "blue-bottle", name: "Blue Bottle Coffee", wiki: "Blue_Bottle_Coffee", category: "brands", emoji: "☕" },
  { id: "stumptown", name: "Stumptown Coffee Roasters", wiki: "Stumptown_Coffee_Roasters", category: "brands", emoji: "☕" },
  { id: "patagonia", name: "Patagonia (clothing)", wiki: "Patagonia,_Inc.", category: "brands", emoji: "🧥" },
  { id: "supreme", name: "Supreme (brand)", wiki: "Supreme_(brand)", category: "brands", emoji: "🧢" },
  { id: "carhartt", name: "Carhartt", wiki: "Carhartt", category: "brands", emoji: "🧥" },
  { id: "moleskine", name: "Moleskine", wiki: "Moleskine", category: "brands", emoji: "📓" },
  { id: "leica", name: "Leica Camera", wiki: "Leica_Camera", category: "brands", emoji: "📷" },
  { id: "muji", name: "Muji", wiki: "Muji", category: "brands", emoji: "📦" },
  { id: "ikea", name: "IKEA", wiki: "IKEA", category: "brands", emoji: "🪑" },
  { id: "nike", name: "Nike, Inc.", wiki: "Nike,_Inc.", category: "brands", emoji: "✔️" },
  { id: "apple", name: "Apple Inc.", wiki: "Apple_Inc.", category: "brands", emoji: "🍎" },
  { id: "amazon", name: "Amazon", wiki: "Amazon_(company)", category: "brands", emoji: "📦" },
  { id: "target", name: "Target", wiki: "Target_Corporation", category: "brands", emoji: "🎯" },
  { id: "walmart", name: "Walmart", wiki: "Walmart", category: "brands", emoji: "🛒" },
  { id: "mcdonalds", name: "McDonald's", wiki: "McDonald%27s", category: "brands", emoji: "🍟" },
  { id: "aesop", name: "Aesop", wiki: "Aesop_(brand)", category: "brands", emoji: "🧴" },
  { id: "glossier", name: "Glossier", wiki: "Glossier", category: "brands", emoji: "💄" },
  { id: "goop", name: "Goop", wiki: "Goop_(company)", category: "brands", emoji: "✨" },
  { id: "stussy", name: "Stüssy", wiki: "St%C3%BCssy", category: "brands", emoji: "👕" },
  { id: "apc", name: "A.P.C.", wiki: "A.P.C.", category: "brands", emoji: "👖" },
  { id: "comme-des-garcons", name: "Comme des Garçons", wiki: "Comme_des_Gar%C3%A7ons", category: "brands", emoji: "👗" },
  { id: "issey-miyake", name: "Issey Miyake", wiki: "Issey_Miyake", category: "brands", emoji: "👘" },
  { id: "ace-hotel", name: "Ace Hotel", wiki: "Ace_Hotel", category: "brands", emoji: "🏨" },
  { id: "equinox", name: "Equinox Group", wiki: "Equinox_Group", category: "brands", emoji: "🏋️" },
  { id: "erewhon", name: "Erewhon", wiki: "Erewhon_Market", category: "brands", emoji: "🥗" },

  // --- hobbies ---
  { id: "knitting", name: "Knitting", wiki: "Knitting", category: "hobbies", emoji: "🧶" },
  { id: "bouldering", name: "Bouldering", wiki: "Bouldering", category: "hobbies", emoji: "🧗" },
  { id: "pottery", name: "Pottery", wiki: "Pottery", category: "hobbies", emoji: "🏺" },
  { id: "birdwatching", name: "Birdwatching", wiki: "Birdwatching", category: "hobbies", emoji: "🦜" },
  { id: "running", name: "Running", wiki: "Running", category: "hobbies", emoji: "🏃" },
  { id: "yoga", name: "Yoga", wiki: "Yoga", category: "hobbies", emoji: "🧘" },
  { id: "pickleball", name: "Pickleball", wiki: "Pickleball", category: "hobbies", emoji: "🏓" },
  { id: "disc-golf", name: "Disc golf", wiki: "Disc_golf", category: "hobbies", emoji: "🥏" },
  { id: "kintsugi", name: "Kintsugi", wiki: "Kintsugi", category: "hobbies", emoji: "🏺" },
  { id: "bonsai", name: "Bonsai", wiki: "Bonsai", category: "hobbies", emoji: "🌳" },
  { id: "golf", name: "Golf", wiki: "Golf", category: "hobbies", emoji: "⛳" },
  { id: "fishing", name: "Fishing", wiki: "Fishing", category: "hobbies", emoji: "🎣" },
  { id: "gardening", name: "Gardening", wiki: "Gardening", category: "hobbies", emoji: "🌻" },
  { id: "hiking", name: "Hiking", wiki: "Hiking", category: "hobbies", emoji: "🥾" },
  { id: "photography", name: "Photography", wiki: "Photography", category: "hobbies", emoji: "📷" },
  { id: "skateboarding", name: "Skateboarding", wiki: "Skateboarding", category: "hobbies", emoji: "🛹" },
  { id: "surfing", name: "Surfing", wiki: "Surfing", category: "hobbies", emoji: "🏄" },
  { id: "foraging", name: "Foraging", wiki: "Foraging", category: "hobbies", emoji: "🍄" },
  { id: "fermentation", name: "Fermentation in food processing", wiki: "Fermentation_in_food_processing", category: "hobbies", emoji: "🫙" },
  { id: "calligraphy", name: "Calligraphy", wiki: "Calligraphy", category: "hobbies", emoji: "🖋️" },
  { id: "embroidery", name: "Embroidery", wiki: "Embroidery", category: "hobbies", emoji: "🧵" },
  { id: "woodworking", name: "Woodworking", wiki: "Woodworking", category: "hobbies", emoji: "🪵" },
  { id: "fly-fishing", name: "Fly fishing", wiki: "Fly_fishing", category: "hobbies", emoji: "🎣" },
  { id: "bikepacking", name: "Bikepacking", wiki: "Bikepacking", category: "hobbies", emoji: "🚴" },
  { id: "vinyl-collecting", name: "Record collecting", wiki: "Record_collecting", category: "hobbies", emoji: "💿" },

  // --- tech ---
  { id: "iphone", name: "iPhone", wiki: "IPhone", category: "tech", emoji: "📱" },
  { id: "linux", name: "Linux", wiki: "Linux", category: "tech", emoji: "🐧" },
  { id: "arch-linux", name: "Arch Linux", wiki: "Arch_Linux", category: "tech", emoji: "🐧" },
  { id: "nixos", name: "NixOS", wiki: "NixOS", category: "tech", emoji: "❄️" },
  { id: "rust-lang", name: "Rust (programming language)", wiki: "Rust_(programming_language)", category: "tech", emoji: "🦀" },
  { id: "javascript", name: "JavaScript", wiki: "JavaScript", category: "tech", emoji: "🟨" },
  { id: "haskell", name: "Haskell", wiki: "Haskell", category: "tech", emoji: "λ" },
  { id: "vim", name: "Vim (text editor)", wiki: "Vim_(text_editor)", category: "tech", emoji: "📝" },
  { id: "emacs", name: "Emacs", wiki: "Emacs", category: "tech", emoji: "📝" },
  { id: "chatgpt", name: "ChatGPT", wiki: "ChatGPT", category: "tech", emoji: "🤖" },
  { id: "windows", name: "Microsoft Windows", wiki: "Microsoft_Windows", category: "tech", emoji: "🪟" },
  { id: "android", name: "Android (operating system)", wiki: "Android_(operating_system)", category: "tech", emoji: "🤖" },
  { id: "macos", name: "macOS", wiki: "MacOS", category: "tech", emoji: "💻" },
  { id: "chrome", name: "Google Chrome", wiki: "Google_Chrome", category: "tech", emoji: "🌐" },
  { id: "photoshop", name: "Adobe Photoshop", wiki: "Adobe_Photoshop", category: "tech", emoji: "🎨" },
  { id: "slack", name: "Slack", wiki: "Slack_(software)", category: "tech", emoji: "💬" },
  { id: "zoom", name: "Zoom", wiki: "Zoom_(software)", category: "tech", emoji: "📹" },
  { id: "elixir", name: "Elixir (programming language)", wiki: "Elixir_(programming_language)", category: "tech", emoji: "💧" },
  { id: "ocaml", name: "OCaml", wiki: "OCaml", category: "tech", emoji: "🐫" },
  { id: "zig", name: "Zig (programming language)", wiki: "Zig_(programming_language)", category: "tech", emoji: "⚡" },
  { id: "neovim", name: "Neovim", wiki: "Neovim", category: "tech", emoji: "📝" },
  { id: "tmux", name: "Tmux", wiki: "Tmux", category: "tech", emoji: "🖥️" },
  { id: "freebsd", name: "FreeBSD", wiki: "FreeBSD", category: "tech", emoji: "😈" },
  { id: "clojure", name: "Clojure", wiki: "Clojure", category: "tech", emoji: "🌀" },
  { id: "erlang", name: "Erlang (programming language)", wiki: "Erlang_(programming_language)", category: "tech", emoji: "📞" },
  { id: "apl", name: "APL (programming language)", wiki: "APL_(programming_language)", category: "tech", emoji: "🔤" },

  // --- animals ---
  { id: "golden-retriever", name: "Golden Retriever", wiki: "Golden_Retriever", category: "animals", emoji: "🐕" },
  { id: "shiba-inu", name: "Shiba Inu", wiki: "Shiba_Inu", category: "animals", emoji: "🐕" },
  { id: "bernedoodle", name: "Bernedoodle", wiki: "Bernedoodle", category: "animals", emoji: "🐕" },
  { id: "axolotl", name: "Axolotl", wiki: "Axolotl", category: "animals", emoji: "🦎" },
  { id: "capybara", name: "Capybara", wiki: "Capybara", category: "animals", emoji: "🐹" },
  { id: "octopus", name: "Octopus", wiki: "Octopus", category: "animals", emoji: "🐙" },
  { id: "ragdoll-cat", name: "Ragdoll", wiki: "Ragdoll", category: "animals", emoji: "🐈" },
  { id: "tardigrade", name: "Tardigrade", wiki: "Tardigrade", category: "animals", emoji: "🦠" },
  { id: "cat", name: "Cat", wiki: "Cat", category: "animals", emoji: "🐈" },
  { id: "dog", name: "Dog", wiki: "Dog", category: "animals", emoji: "🐕" },
  { id: "horse", name: "Horse", wiki: "Horse", category: "animals", emoji: "🐎" },
  { id: "lion", name: "Lion", wiki: "Lion", category: "animals", emoji: "🦁" },
  { id: "tiger", name: "Tiger", wiki: "Tiger", category: "animals", emoji: "🐅" },
  { id: "elephant", name: "Elephant", wiki: "Elephant", category: "animals", emoji: "🐘" },
  { id: "dolphin", name: "Dolphin", wiki: "Dolphin", category: "animals", emoji: "🐬" },
  { id: "fox", name: "Fox", wiki: "Fox", category: "animals", emoji: "🦊" },
  { id: "panda", name: "Giant panda", wiki: "Giant_panda", category: "animals", emoji: "🐼" },
  { id: "koala", name: "Koala", wiki: "Koala", category: "animals", emoji: "🐨" },
  { id: "penguin", name: "Penguin", wiki: "Penguin", category: "animals", emoji: "🐧" },
  { id: "corgi", name: "Pembroke Welsh Corgi", wiki: "Pembroke_Welsh_Corgi", category: "animals", emoji: "🐕" },
  { id: "dachshund", name: "Dachshund", wiki: "Dachshund", category: "animals", emoji: "🐕" },
  { id: "sphynx-cat", name: "Sphynx cat", wiki: "Sphynx_cat", category: "animals", emoji: "🐈" },
  { id: "maine-coon", name: "Maine Coon", wiki: "Maine_Coon", category: "animals", emoji: "🐈" },
  { id: "hedgehog", name: "Hedgehog", wiki: "Hedgehog", category: "animals", emoji: "🦔" },
  { id: "pangolin", name: "Pangolin", wiki: "Pangolin", category: "animals", emoji: "🦔" },
  { id: "narwhal", name: "Narwhal", wiki: "Narwhal", category: "animals", emoji: "🦄" },
  { id: "quokka", name: "Quokka", wiki: "Quokka", category: "animals", emoji: "🐹" },
  { id: "kakapo", name: "Kākāpō", wiki: "K%C4%81k%C4%81p%C5%8D", category: "animals", emoji: "🦜" },
  { id: "mantis-shrimp", name: "Mantis shrimp", wiki: "Mantis_shrimp", category: "animals", emoji: "🦐" },
];

export function itemsByCategory(category: Category | "mixed"): Item[] {
  if (category === "mixed") return ITEMS;
  return ITEMS.filter((i) => i.category === category);
}

export const CATEGORIES: { id: Category | "mixed"; label: string; emoji: string }[] = [
  { id: "mixed", label: "Mixed Bag", emoji: "🎲" },
  { id: "music", label: "Music", emoji: "🎸" },
  { id: "food", label: "Food", emoji: "🍕" },
  { id: "drinks", label: "Drinks", emoji: "☕" },
  { id: "cities", label: "Cities", emoji: "🏙️" },
  { id: "movies", label: "Movies", emoji: "🎬" },
  { id: "tv", label: "TV Shows", emoji: "📺" },
  { id: "books", label: "Books", emoji: "📚" },
  { id: "brands", label: "Brands", emoji: "🛍️" },
  { id: "hobbies", label: "Hobbies", emoji: "🧶" },
  { id: "tech", label: "Tech", emoji: "💻" },
  { id: "animals", label: "Animals", emoji: "🐙" },
];
