import type { Category, Item } from "./types";

// Curated bank. `wiki` is the exact Wikipedia article title (URL-encoded by the API client).
// Underscores are fine; the REST API accepts them.
// Every slug has been verified to return >0 pageviews from the Wikimedia API.
export const ITEMS: Item[] = [
  // --- music ---
  { id: "taylor-swift", name: "Taylor Swift", wiki: "Taylor_Swift", category: "music", emoji: "🎤" },
  { id: "the-beatles", name: "The Beatles", wiki: "The_Beatles", category: "music", emoji: "🎸" },
  { id: "drake", name: "Drake", wiki: "Drake_(musician)", category: "music", emoji: "🎤" },
  { id: "billie-eilish", name: "Billie Eilish", wiki: "Billie_Eilish", category: "music", emoji: "🎤" },
  { id: "beyonce", name: "Beyoncé", wiki: "Beyonc%C3%A9", category: "music", emoji: "🎤" },
  { id: "bad-bunny", name: "Bad Bunny", wiki: "Bad_Bunny", category: "music", emoji: "🎤" },
  { id: "bts", name: "BTS", wiki: "BTS", category: "music", emoji: "🎤" },
  { id: "olivia-rodrigo", name: "Olivia Rodrigo", wiki: "Olivia_Rodrigo", category: "music", emoji: "🎤" },
  { id: "harry-styles", name: "Harry Styles", wiki: "Harry_Styles", category: "music", emoji: "🎤" },
  { id: "ed-sheeran", name: "Ed Sheeran", wiki: "Ed_Sheeran", category: "music", emoji: "🎸" },
  { id: "adele", name: "Adele", wiki: "Adele", category: "music", emoji: "🎤" },
  { id: "the-weeknd", name: "The Weeknd", wiki: "The_Weeknd", category: "music", emoji: "🎤" },
  { id: "bob-dylan", name: "Bob Dylan", wiki: "Bob_Dylan", category: "music", emoji: "🎸" },
  { id: "david-bowie", name: "David Bowie", wiki: "David_Bowie", category: "music", emoji: "🎤" },
  { id: "pink-floyd", name: "Pink Floyd", wiki: "Pink_Floyd", category: "music", emoji: "🎸" },
  { id: "nirvana", name: "Nirvana", wiki: "Nirvana_(band)", category: "music", emoji: "🎸" },
  { id: "queen", name: "Queen", wiki: "Queen_(band)", category: "music", emoji: "🎸" },
  { id: "phoebe-bridgers", name: "Phoebe Bridgers", wiki: "Phoebe_Bridgers", category: "music", emoji: "🎤" },
  { id: "mitski", name: "Mitski", wiki: "Mitski", category: "music", emoji: "🎤" },
  { id: "japanese-breakfast", name: "Japanese Breakfast", wiki: "Japanese_Breakfast", category: "music", emoji: "🎤" },
  { id: "alvvays", name: "Alvvays", wiki: "Alvvays", category: "music", emoji: "🎸" },
  { id: "big-thief", name: "Big Thief", wiki: "Big_Thief", category: "music", emoji: "🎸" },
  { id: "bon-iver", name: "Bon Iver", wiki: "Bon_Iver", category: "music", emoji: "🎸" },
  { id: "vampire-weekend", name: "Vampire Weekend", wiki: "Vampire_Weekend", category: "music", emoji: "🎸" },
  { id: "arcade-fire", name: "Arcade Fire", wiki: "Arcade_Fire", category: "music", emoji: "🎸" },
  { id: "radiohead", name: "Radiohead", wiki: "Radiohead", category: "music", emoji: "🎸" },
  { id: "fleetwood-mac", name: "Fleetwood Mac", wiki: "Fleetwood_Mac", category: "music", emoji: "🎸" },
  { id: "kanye-west", name: "Kanye West", wiki: "Kanye_West", category: "music", emoji: "🎤" },
  { id: "frank-ocean", name: "Frank Ocean", wiki: "Frank_Ocean", category: "music", emoji: "🎤" },
  { id: "tyler-the-creator", name: "Tyler, the Creator", wiki: "Tyler,_the_Creator", category: "music", emoji: "🎤" },
  { id: "king-gizzard", name: "King Gizzard & the Lizard Wizard", wiki: "King_Gizzard_%26_the_Lizard_Wizard", category: "music", emoji: "🎸" },
  { id: "weyes-blood", name: "Weyes Blood", wiki: "Weyes_Blood", category: "music", emoji: "🎤" },
  { id: "sufjan-stevens", name: "Sufjan Stevens", wiki: "Sufjan_Stevens", category: "music", emoji: "🎸" },
  { id: "soccer-mommy", name: "Soccer Mommy", wiki: "Soccer_Mommy", category: "music", emoji: "🎸" },
  { id: "snail-mail", name: "Snail Mail", wiki: "Snail_Mail_(musician)", category: "music", emoji: "🎤" },
  { id: "faye-webster", name: "Faye Webster", wiki: "Faye_Webster", category: "music", emoji: "🎤" },
  { id: "black-country-new-road", name: "Black Country, New Road", wiki: "Black_Country,_New_Road", category: "music", emoji: "🎸" },
  { id: "caroline-polachek", name: "Caroline Polachek", wiki: "Caroline_Polachek", category: "music", emoji: "🎤" },
  { id: "cocteau-twins", name: "Cocteau Twins", wiki: "Cocteau_Twins", category: "music", emoji: "🎸" },
  { id: "my-bloody-valentine", name: "My Bloody Valentine", wiki: "My_Bloody_Valentine_(band)", category: "music", emoji: "🎸" },
  { id: "slowdive", name: "Slowdive", wiki: "Slowdive", category: "music", emoji: "🎸" },
  { id: "beach-house", name: "Beach House", wiki: "Beach_House", category: "music", emoji: "🎸" },
  { id: "mac-demarco", name: "Mac DeMarco", wiki: "Mac_DeMarco", category: "music", emoji: "🎸" },
  { id: "tame-impala", name: "Tame Impala", wiki: "Tame_Impala", category: "music", emoji: "🎸" },
  { id: "father-john-misty", name: "Father John Misty", wiki: "Father_John_Misty", category: "music", emoji: "🎸" },
  { id: "st-vincent", name: "St. Vincent", wiki: "St._Vincent_(musician)", category: "music", emoji: "🎸" },
  { id: "daft-punk", name: "Daft Punk", wiki: "Daft_Punk", category: "music", emoji: "🎛️" },
  { id: "aphex-twin", name: "Aphex Twin", wiki: "Aphex_Twin", category: "music", emoji: "🎛️" },
  { id: "boards-of-canada", name: "Boards of Canada", wiki: "Boards_of_Canada", category: "music", emoji: "🎛️" },

  // --- food ---
  { id: "pizza", name: "Pizza", wiki: "Pizza", category: "food", emoji: "🍕" },
  { id: "sushi", name: "Sushi", wiki: "Sushi", category: "food", emoji: "🍣" },
  { id: "ramen", name: "Ramen", wiki: "Ramen", category: "food", emoji: "🍜" },
  { id: "pho", name: "Phở", wiki: "Pho", category: "food", emoji: "🍜" },
  { id: "kimchi", name: "Kimchi", wiki: "Kimchi", category: "food", emoji: "🥬" },
  { id: "natto", name: "Nattō", wiki: "Natt%C5%8D", category: "food", emoji: "🫘" },
  { id: "kombucha", name: "Kombucha", wiki: "Kombucha", category: "food", emoji: "🍵" },
  { id: "avocado-toast", name: "Avocado toast", wiki: "Avocado_toast", category: "food", emoji: "🥑" },
  { id: "burger", name: "Hamburger", wiki: "Hamburger", category: "food", emoji: "🍔" },
  { id: "tacos", name: "Taco", wiki: "Taco", category: "food", emoji: "🌮" },
  { id: "poke", name: "Poke", wiki: "Poke_(dish)", category: "food", emoji: "🐟" },
  { id: "ceviche", name: "Ceviche", wiki: "Ceviche", category: "food", emoji: "🐟" },
  { id: "shakshuka", name: "Shakshouka", wiki: "Shakshouka", category: "food", emoji: "🍳" },
  { id: "miso-soup", name: "Miso soup", wiki: "Miso_soup", category: "food", emoji: "🍜" },
  { id: "kouign-amann", name: "Kouign-amann", wiki: "Kouign-amann", category: "food", emoji: "🥐" },
  { id: "croissant", name: "Croissant", wiki: "Croissant", category: "food", emoji: "🥐" },
  { id: "biryani", name: "Biryani", wiki: "Biryani", category: "food", emoji: "🍛" },
  { id: "butter-chicken", name: "Butter chicken", wiki: "Butter_chicken", category: "food", emoji: "🍛" },
  { id: "dosa", name: "Dosa", wiki: "Dosa", category: "food", emoji: "🥞" },
  { id: "carbonara", name: "Carbonara", wiki: "Carbonara", category: "food", emoji: "🍝" },
  { id: "lasagna", name: "Lasagna", wiki: "Lasagna", category: "food", emoji: "🍝" },
  { id: "risotto", name: "Risotto", wiki: "Risotto", category: "food", emoji: "🍚" },
  { id: "cacio-e-pepe", name: "Cacio e pepe", wiki: "Cacio_e_pepe", category: "food", emoji: "🍝" },
  { id: "mole", name: "Mole", wiki: "Mole_(sauce)", category: "food", emoji: "🌶️" },
  { id: "pupusa", name: "Pupusa", wiki: "Pupusa", category: "food", emoji: "🫓" },
  { id: "arepa", name: "Arepa", wiki: "Arepa", category: "food", emoji: "🫓" },
  { id: "bibimbap", name: "Bibimbap", wiki: "Bibimbap", category: "food", emoji: "🍲" },
  { id: "banh-mi", name: "Bánh mì", wiki: "B%C3%A1nh_m%C3%AC", category: "food", emoji: "🥖" },
  { id: "laksa", name: "Laksa", wiki: "Laksa", category: "food", emoji: "🍜" },
  { id: "pad-thai", name: "Pad thai", wiki: "Pad_thai", category: "food", emoji: "🍜" },
  { id: "dim-sum", name: "Dim sum", wiki: "Dim_sum", category: "food", emoji: "🥟" },
  { id: "takoyaki", name: "Takoyaki", wiki: "Takoyaki", category: "food", emoji: "🐙" },
  { id: "tonkatsu", name: "Tonkatsu", wiki: "Tonkatsu", category: "food", emoji: "🍱" },
  { id: "sourdough", name: "Sourdough", wiki: "Sourdough", category: "food", emoji: "🍞" },
  { id: "tahini", name: "Tahini", wiki: "Tahini", category: "food", emoji: "🥣" },
  { id: "french-fries", name: "French fries", wiki: "French_fries", category: "food", emoji: "🍟" },
  { id: "fried-chicken", name: "Fried chicken", wiki: "Fried_chicken", category: "food", emoji: "🍗" },
  { id: "durian", name: "Durian", wiki: "Durian", category: "food", emoji: "🥥" },

  // --- cities ---
  { id: "new-york", name: "New York City", wiki: "New_York_City", category: "cities", emoji: "🗽" },
  { id: "paris", name: "Paris", wiki: "Paris", category: "cities", emoji: "🗼" },
  { id: "tokyo", name: "Tokyo", wiki: "Tokyo", category: "cities", emoji: "🗾" },
  { id: "london", name: "London", wiki: "London", category: "cities", emoji: "🎡" },
  { id: "berlin", name: "Berlin", wiki: "Berlin", category: "cities", emoji: "🍻" },
  { id: "portland", name: "Portland, Oregon", wiki: "Portland,_Oregon", category: "cities", emoji: "🌲" },
  { id: "austin", name: "Austin, Texas", wiki: "Austin,_Texas", category: "cities", emoji: "🤠" },
  { id: "asheville", name: "Asheville, North Carolina", wiki: "Asheville,_North_Carolina", category: "cities", emoji: "🏔️" },
  { id: "marfa", name: "Marfa, Texas", wiki: "Marfa,_Texas", category: "cities", emoji: "🎨" },
  { id: "reykjavik", name: "Reykjavík", wiki: "Reykjav%C3%ADk", category: "cities", emoji: "❄️" },
  { id: "lisbon", name: "Lisbon", wiki: "Lisbon", category: "cities", emoji: "🌊" },
  { id: "copenhagen", name: "Copenhagen", wiki: "Copenhagen", category: "cities", emoji: "🚲" },
  { id: "tulum", name: "Tulum", wiki: "Tulum", category: "cities", emoji: "🌴" },
  { id: "oaxaca", name: "Oaxaca City", wiki: "Oaxaca_City", category: "cities", emoji: "🌶️" },
  { id: "los-angeles", name: "Los Angeles", wiki: "Los_Angeles", category: "cities", emoji: "🌴" },
  { id: "chicago", name: "Chicago", wiki: "Chicago", category: "cities", emoji: "🏙️" },
  { id: "san-francisco", name: "San Francisco", wiki: "San_Francisco", category: "cities", emoji: "🌉" },
  { id: "miami", name: "Miami", wiki: "Miami", category: "cities", emoji: "🌴" },
  { id: "las-vegas", name: "Las Vegas", wiki: "Las_Vegas", category: "cities", emoji: "🎰" },
  { id: "seattle", name: "Seattle", wiki: "Seattle", category: "cities", emoji: "🏔️" },
  { id: "boston", name: "Boston", wiki: "Boston", category: "cities", emoji: "🦞" },
  { id: "toronto", name: "Toronto", wiki: "Toronto", category: "cities", emoji: "🍁" },
  { id: "mexico-city", name: "Mexico City", wiki: "Mexico_City", category: "cities", emoji: "🌮" },
  { id: "rome", name: "Rome", wiki: "Rome", category: "cities", emoji: "🏛️" },
  { id: "barcelona", name: "Barcelona", wiki: "Barcelona", category: "cities", emoji: "🏖️" },
  { id: "amsterdam", name: "Amsterdam", wiki: "Amsterdam", category: "cities", emoji: "🚲" },
  { id: "bangkok", name: "Bangkok", wiki: "Bangkok", category: "cities", emoji: "🛺" },
  { id: "dubai", name: "Dubai", wiki: "Dubai", category: "cities", emoji: "🏗️" },
  { id: "sydney", name: "Sydney", wiki: "Sydney", category: "cities", emoji: "🦘" },
  { id: "hong-kong", name: "Hong Kong", wiki: "Hong_Kong", category: "cities", emoji: "🏙️" },
  { id: "mumbai", name: "Mumbai", wiki: "Mumbai", category: "cities", emoji: "🇮🇳" },
  { id: "porto", name: "Porto", wiki: "Porto", category: "cities", emoji: "🍷" },
  { id: "cape-town", name: "Cape Town", wiki: "Cape_Town", category: "cities", emoji: "🏔️" },
  { id: "tbilisi", name: "Tbilisi", wiki: "Tbilisi", category: "cities", emoji: "🍷" },
  { id: "tallinn", name: "Tallinn", wiki: "Tallinn", category: "cities", emoji: "🏰" },
  { id: "hanoi", name: "Hanoi", wiki: "Hanoi", category: "cities", emoji: "🥢" },
  { id: "antwerp", name: "Antwerp", wiki: "Antwerp", category: "cities", emoji: "💎" },
  { id: "joshua-tree", name: "Joshua Tree, California", wiki: "Joshua_Tree,_California", category: "cities", emoji: "🌵" },
  { id: "hudson-ny", name: "Hudson, New York", wiki: "Hudson,_New_York", category: "cities", emoji: "🏘️" },
  { id: "provincetown", name: "Provincetown, Massachusetts", wiki: "Provincetown,_Massachusetts", category: "cities", emoji: "🏖️" },

  // --- movies ---
  { id: "titanic", name: "Titanic (1997 film)", wiki: "Titanic_(1997_film)", category: "movies", emoji: "🚢" },
  { id: "avengers-endgame", name: "Avengers: Endgame", wiki: "Avengers:_Endgame", category: "movies", emoji: "🦸" },
  { id: "barbie", name: "Barbie (film)", wiki: "Barbie_(film)", category: "movies", emoji: "👱‍♀️" },
  { id: "oppenheimer", name: "Oppenheimer (film)", wiki: "Oppenheimer_(film)", category: "movies", emoji: "💥" },
  { id: "parasite", name: "Parasite (2019 film)", wiki: "Parasite_(2019_film)", category: "movies", emoji: "🎬" },
  { id: "everything-everywhere", name: "Everything Everywhere All at Once", wiki: "Everything_Everywhere_All_at_Once", category: "movies", emoji: "🥯" },
  { id: "the-lighthouse", name: "The Lighthouse (2019 film)", wiki: "The_Lighthouse_(2019_film)", category: "movies", emoji: "🦞" },
  { id: "midsommar", name: "Midsommar (film)", wiki: "Midsommar_(film)", category: "movies", emoji: "🌼" },
  { id: "moonlight", name: "Moonlight (2016 film)", wiki: "Moonlight_(2016_film)", category: "movies", emoji: "🌙" },
  { id: "the-favourite", name: "The Favourite", wiki: "The_Favourite", category: "movies", emoji: "👑" },
  { id: "frances-ha", name: "Frances Ha", wiki: "Frances_Ha", category: "movies", emoji: "💃" },
  { id: "lady-bird", name: "Lady Bird (film)", wiki: "Lady_Bird_(film)", category: "movies", emoji: "🐦" },
  { id: "inception", name: "Inception", wiki: "Inception", category: "movies", emoji: "🌀" },
  { id: "the-dark-knight", name: "The Dark Knight", wiki: "The_Dark_Knight", category: "movies", emoji: "🦇" },
  { id: "avatar", name: "Avatar (2009 film)", wiki: "Avatar_(2009_film)", category: "movies", emoji: "🌌" },
  { id: "pulp-fiction", name: "Pulp Fiction", wiki: "Pulp_Fiction", category: "movies", emoji: "🔫" },
  { id: "interstellar", name: "Interstellar (film)", wiki: "Interstellar_(film)", category: "movies", emoji: "🪐" },
  { id: "the-godfather", name: "The Godfather", wiki: "The_Godfather", category: "movies", emoji: "🎩" },
  { id: "forrest-gump", name: "Forrest Gump", wiki: "Forrest_Gump", category: "movies", emoji: "🏃" },
  { id: "aftersun", name: "Aftersun", wiki: "Aftersun", category: "movies", emoji: "📼" },
  { id: "past-lives", name: "Past Lives (film)", wiki: "Past_Lives_(film)", category: "movies", emoji: "✨" },
  { id: "uncut-gems", name: "Uncut Gems", wiki: "Uncut_Gems", category: "movies", emoji: "💎" },
  { id: "burning", name: "Burning (2018 film)", wiki: "Burning_(2018_film)", category: "movies", emoji: "🔥" },
  { id: "drive-my-car", name: "Drive My Car (film)", wiki: "Drive_My_Car_(film)", category: "movies", emoji: "🚗" },
  { id: "petite-maman", name: "Petite Maman", wiki: "Petite_Maman", category: "movies", emoji: "👧" },
  { id: "first-cow", name: "First Cow", wiki: "First_Cow", category: "movies", emoji: "🐄" },
  { id: "minari", name: "Minari (film)", wiki: "Minari_(film)", category: "movies", emoji: "🌱" },
  { id: "the-power-of-the-dog", name: "The Power of the Dog (film)", wiki: "The_Power_of_the_Dog_(film)", category: "movies", emoji: "🐕" },
  { id: "nomadland", name: "Nomadland", wiki: "Nomadland", category: "movies", emoji: "🚐" },
  { id: "the-florida-project", name: "The Florida Project", wiki: "The_Florida_Project", category: "movies", emoji: "🏨" },

  // --- tv ---
  { id: "friends", name: "Friends", wiki: "Friends", category: "tv", emoji: "📺" },
  { id: "the-office", name: "The Office (American TV series)", wiki: "The_Office_(American_TV_series)", category: "tv", emoji: "📎" },
  { id: "game-of-thrones", name: "Game of Thrones", wiki: "Game_of_Thrones", category: "tv", emoji: "🐉" },
  { id: "stranger-things", name: "Stranger Things", wiki: "Stranger_Things", category: "tv", emoji: "🔦" },
  { id: "breaking-bad", name: "Breaking Bad", wiki: "Breaking_Bad", category: "tv", emoji: "🧪" },
  { id: "mad-men", name: "Mad Men", wiki: "Mad_Men", category: "tv", emoji: "🥃" },
  { id: "succession", name: "Succession (TV series)", wiki: "Succession_(TV_series)", category: "tv", emoji: "🏛️" },
  { id: "atlanta-tv", name: "Atlanta (TV series)", wiki: "Atlanta_(TV_series)", category: "tv", emoji: "🍑" },
  { id: "severance", name: "Severance (TV series)", wiki: "Severance_(TV_series)", category: "tv", emoji: "🧠" },
  { id: "the-bear", name: "The Bear (TV series)", wiki: "The_Bear_(TV_series)", category: "tv", emoji: "🐻" },
  { id: "fleabag", name: "Fleabag", wiki: "Fleabag", category: "tv", emoji: "🦊" },
  { id: "better-call-saul", name: "Better Call Saul", wiki: "Better_Call_Saul", category: "tv", emoji: "⚖️" },
  { id: "bojack-horseman", name: "BoJack Horseman", wiki: "BoJack_Horseman", category: "tv", emoji: "🐴" },
  { id: "twin-peaks", name: "Twin Peaks", wiki: "Twin_Peaks", category: "tv", emoji: "🌲" },
  { id: "the-sopranos", name: "The Sopranos", wiki: "The_Sopranos", category: "tv", emoji: "🍝" },
  { id: "curb-your-enthusiasm", name: "Curb Your Enthusiasm", wiki: "Curb_Your_Enthusiasm", category: "tv", emoji: "😤" },
  { id: "i-think-you-should-leave", name: "I Think You Should Leave with Tim Robinson", wiki: "I_Think_You_Should_Leave_with_Tim_Robinson", category: "tv", emoji: "🚪" },
  { id: "reservation-dogs", name: "Reservation Dogs", wiki: "Reservation_Dogs", category: "tv", emoji: "🐕" },
  { id: "mr-robot", name: "Mr. Robot", wiki: "Mr._Robot", category: "tv", emoji: "🤖" },
  { id: "yellowjackets", name: "Yellowjackets (TV series)", wiki: "Yellowjackets_(TV_series)", category: "tv", emoji: "🐝" },
  { id: "the-wire", name: "The Wire", wiki: "The_Wire", category: "tv", emoji: "📞" },
  { id: "lost", name: "Lost (TV series)", wiki: "Lost_(TV_series)", category: "tv", emoji: "🏝️" },
  { id: "the-mandalorian", name: "The Mandalorian", wiki: "The_Mandalorian", category: "tv", emoji: "👶" },
  { id: "bluey", name: "Bluey", wiki: "Bluey_(2018_TV_series)", category: "tv", emoji: "🐶" },

  // --- books ---
  { id: "harry-potter", name: "Harry Potter", wiki: "Harry_Potter", category: "books", emoji: "⚡" },
  { id: "the-great-gatsby", name: "The Great Gatsby", wiki: "The_Great_Gatsby", category: "books", emoji: "🥂" },
  { id: "1984-book", name: "Nineteen Eighty-Four", wiki: "Nineteen_Eighty-Four", category: "books", emoji: "👁️" },
  { id: "lotr", name: "The Lord of the Rings", wiki: "The_Lord_of_the_Rings", category: "books", emoji: "💍" },
  { id: "to-kill-a-mockingbird", name: "To Kill a Mockingbird", wiki: "To_Kill_a_Mockingbird", category: "books", emoji: "🐦" },
  { id: "the-hunger-games", name: "The Hunger Games", wiki: "The_Hunger_Games", category: "books", emoji: "🏹" },
  { id: "the-catcher-in-the-rye", name: "The Catcher in the Rye", wiki: "The_Catcher_in_the_Rye", category: "books", emoji: "🧢" },
  { id: "pride-and-prejudice", name: "Pride and Prejudice", wiki: "Pride_and_Prejudice", category: "books", emoji: "💌" },
  { id: "infinite-jest", name: "Infinite Jest", wiki: "Infinite_Jest", category: "books", emoji: "🎾" },
  { id: "normal-people", name: "Normal People (novel)", wiki: "Normal_People", category: "books", emoji: "💔" },
  { id: "my-year-of-rest", name: "My Year of Rest and Relaxation", wiki: "My_Year_of_Rest_and_Relaxation", category: "books", emoji: "💊" },
  { id: "just-kids", name: "Just Kids", wiki: "Just_Kids", category: "books", emoji: "📷" },
  { id: "crying-in-h-mart", name: "Crying in H Mart", wiki: "Crying_in_H_Mart", category: "books", emoji: "😢" },
  { id: "pachinko", name: "Pachinko (novel)", wiki: "Pachinko_(novel)", category: "books", emoji: "🎰" },
  { id: "the-secret-history", name: "The Secret History", wiki: "The_Secret_History", category: "books", emoji: "🏛️" },
  { id: "tomorrow-tomorrow", name: "Tomorrow, and Tomorrow, and Tomorrow (novel)", wiki: "Tomorrow,_and_Tomorrow,_and_Tomorrow_(novel)", category: "books", emoji: "🎮" },
  { id: "beloved", name: "Beloved (novel)", wiki: "Beloved_(novel)", category: "books", emoji: "📖" },
  { id: "the-road", name: "The Road", wiki: "The_Road", category: "books", emoji: "🛣️" },
  { id: "lincoln-in-the-bardo", name: "Lincoln in the Bardo", wiki: "Lincoln_in_the_Bardo", category: "books", emoji: "🎩" },
  { id: "a-little-life", name: "A Little Life", wiki: "A_Little_Life", category: "books", emoji: "💔" },
  { id: "atomic-habits", name: "Atomic Habits", wiki: "Atomic_Habits", category: "books", emoji: "⚛️" },
  { id: "sapiens", name: "Sapiens: A Brief History of Humankind", wiki: "Sapiens:_A_Brief_History_of_Humankind", category: "books", emoji: "🧠" },
  { id: "the-alchemist", name: "The Alchemist", wiki: "The_Alchemist_(novel)", category: "books", emoji: "🪄" },
  { id: "where-the-crawdads-sing", name: "Where the Crawdads Sing", wiki: "Where_the_Crawdads_Sing", category: "books", emoji: "🦞" },

  // --- drinks ---
  { id: "coffee", name: "Coffee", wiki: "Coffee", category: "drinks", emoji: "☕" },
  { id: "espresso", name: "Espresso", wiki: "Espresso", category: "drinks", emoji: "☕" },
  { id: "matcha", name: "Matcha", wiki: "Matcha", category: "drinks", emoji: "🍵" },
  { id: "yerba-mate", name: "Yerba mate", wiki: "Yerba_mate", category: "drinks", emoji: "🧉" },
  { id: "natural-wine", name: "Natural wine", wiki: "Natural_wine", category: "drinks", emoji: "🍷" },
  { id: "negroni", name: "Negroni", wiki: "Negroni", category: "drinks", emoji: "🍸" },
  { id: "aperol-spritz", name: "Aperol Spritz", wiki: "Spritz_Veneziano", category: "drinks", emoji: "🥂" },
  { id: "ipa", name: "India pale ale", wiki: "India_pale_ale", category: "drinks", emoji: "🍺" },
  { id: "mezcal", name: "Mezcal", wiki: "Mezcal", category: "drinks", emoji: "🌵" },
  { id: "soju", name: "Soju", wiki: "Soju", category: "drinks", emoji: "🍶" },
  { id: "coca-cola", name: "Coca-Cola", wiki: "Coca-Cola", category: "drinks", emoji: "🥤" },
  { id: "beer", name: "Beer", wiki: "Beer", category: "drinks", emoji: "🍺" },
  { id: "wine", name: "Wine", wiki: "Wine", category: "drinks", emoji: "🍷" },
  { id: "tea", name: "Tea", wiki: "Tea", category: "drinks", emoji: "🍵" },
  { id: "old-fashioned", name: "Old Fashioned", wiki: "Old_fashioned_(cocktail)", category: "drinks", emoji: "🥃" },
  { id: "martini", name: "Martini", wiki: "Martini_(cocktail)", category: "drinks", emoji: "🍸" },
  { id: "margarita", name: "Margarita", wiki: "Margarita", category: "drinks", emoji: "🍹" },
  { id: "cortado", name: "Cortado", wiki: "Cortado", category: "drinks", emoji: "☕" },
  { id: "flat-white", name: "Flat white", wiki: "Flat_white", category: "drinks", emoji: "☕" },
  { id: "sake", name: "Sake", wiki: "Sake", category: "drinks", emoji: "🍶" },
  { id: "chartreuse", name: "Chartreuse", wiki: "Chartreuse_(liqueur)", category: "drinks", emoji: "💚" },
  { id: "fernet-branca", name: "Fernet-Branca", wiki: "Fernet-Branca", category: "drinks", emoji: "🥃" },
  { id: "amaro", name: "Amaro", wiki: "Amaro_(liqueur)", category: "drinks", emoji: "🥃" },
  { id: "pisco", name: "Pisco", wiki: "Pisco", category: "drinks", emoji: "🇵🇪" },

  // --- brands ---
  { id: "starbucks", name: "Starbucks", wiki: "Starbucks", category: "brands", emoji: "☕" },
  { id: "blue-bottle", name: "Blue Bottle Coffee", wiki: "Blue_Bottle_Coffee", category: "brands", emoji: "☕" },
  { id: "stumptown", name: "Stumptown Coffee Roasters", wiki: "Stumptown_Coffee_Roasters", category: "brands", emoji: "☕" },
  { id: "patagonia", name: "Patagonia (clothing)", wiki: "Patagonia,_Inc.", category: "brands", emoji: "🧥" },
  { id: "supreme", name: "Supreme (brand)", wiki: "Supreme_(brand)", category: "brands", emoji: "🧢" },
  { id: "carhartt", name: "Carhartt", wiki: "Carhartt", category: "brands", emoji: "🧥" },
  { id: "moleskine", name: "Moleskine", wiki: "Moleskine", category: "brands", emoji: "📓" },
  { id: "leica", name: "Leica Camera", wiki: "Leica_Camera", category: "brands", emoji: "📷" },
  { id: "muji", name: "Muji", wiki: "Muji", category: "brands", emoji: "📦" },
  { id: "ikea", name: "IKEA", wiki: "IKEA", category: "brands", emoji: "🪑" },
  { id: "nike", name: "Nike, Inc.", wiki: "Nike,_Inc.", category: "brands", emoji: "✔️" },
  { id: "apple", name: "Apple Inc.", wiki: "Apple_Inc.", category: "brands", emoji: "🍎" },
  { id: "amazon", name: "Amazon", wiki: "Amazon_(company)", category: "brands", emoji: "📦" },
  { id: "target", name: "Target", wiki: "Target_Corporation", category: "brands", emoji: "🎯" },
  { id: "walmart", name: "Walmart", wiki: "Walmart", category: "brands", emoji: "🛒" },
  { id: "mcdonalds", name: "McDonald's", wiki: "McDonald%27s", category: "brands", emoji: "🍟" },
  { id: "aesop", name: "Aesop", wiki: "Aesop_(brand)", category: "brands", emoji: "🧴" },
  { id: "glossier", name: "Glossier", wiki: "Glossier", category: "brands", emoji: "💄" },
  { id: "goop", name: "Goop", wiki: "Goop_(company)", category: "brands", emoji: "✨" },
  { id: "stussy", name: "Stüssy", wiki: "St%C3%BCssy", category: "brands", emoji: "👕" },
  { id: "apc", name: "A.P.C.", wiki: "A.P.C.", category: "brands", emoji: "👖" },
  { id: "comme-des-garcons", name: "Comme des Garçons", wiki: "Comme_des_Gar%C3%A7ons", category: "brands", emoji: "👗" },
  { id: "issey-miyake", name: "Issey Miyake", wiki: "Issey_Miyake", category: "brands", emoji: "👘" },
  { id: "ace-hotel", name: "Ace Hotel", wiki: "Ace_Hotel", category: "brands", emoji: "🏨" },
  { id: "equinox", name: "Equinox Group", wiki: "Equinox_Group", category: "brands", emoji: "🏋️" },
  { id: "erewhon", name: "Erewhon", wiki: "Erewhon_Market", category: "brands", emoji: "🥗" },

  // --- hobbies ---
  { id: "knitting", name: "Knitting", wiki: "Knitting", category: "hobbies", emoji: "🧶" },
  { id: "bouldering", name: "Bouldering", wiki: "Bouldering", category: "hobbies", emoji: "🧗" },
  { id: "pottery", name: "Pottery", wiki: "Pottery", category: "hobbies", emoji: "🏺" },
  { id: "birdwatching", name: "Birdwatching", wiki: "Birdwatching", category: "hobbies", emoji: "🦜" },
  { id: "running", name: "Running", wiki: "Running", category: "hobbies", emoji: "🏃" },
  { id: "yoga", name: "Yoga", wiki: "Yoga", category: "hobbies", emoji: "🧘" },
  { id: "pickleball", name: "Pickleball", wiki: "Pickleball", category: "hobbies", emoji: "🏓" },
  { id: "disc-golf", name: "Disc golf", wiki: "Disc_golf", category: "hobbies", emoji: "🥏" },
  { id: "kintsugi", name: "Kintsugi", wiki: "Kintsugi", category: "hobbies", emoji: "🏺" },
  { id: "bonsai", name: "Bonsai", wiki: "Bonsai", category: "hobbies", emoji: "🌳" },
  { id: "golf", name: "Golf", wiki: "Golf", category: "hobbies", emoji: "⛳" },
  { id: "fishing", name: "Fishing", wiki: "Fishing", category: "hobbies", emoji: "🎣" },
  { id: "gardening", name: "Gardening", wiki: "Gardening", category: "hobbies", emoji: "🌻" },
  { id: "hiking", name: "Hiking", wiki: "Hiking", category: "hobbies", emoji: "🥾" },
  { id: "photography", name: "Photography", wiki: "Photography", category: "hobbies", emoji: "📷" },
  { id: "skateboarding", name: "Skateboarding", wiki: "Skateboarding", category: "hobbies", emoji: "🛹" },
  { id: "surfing", name: "Surfing", wiki: "Surfing", category: "hobbies", emoji: "🏄" },
  { id: "foraging", name: "Foraging", wiki: "Foraging", category: "hobbies", emoji: "🍄" },
  { id: "fermentation", name: "Fermentation in food processing", wiki: "Fermentation_in_food_processing", category: "hobbies", emoji: "🫙" },
  { id: "calligraphy", name: "Calligraphy", wiki: "Calligraphy", category: "hobbies", emoji: "🖋️" },
  { id: "embroidery", name: "Embroidery", wiki: "Embroidery", category: "hobbies", emoji: "🧵" },
  { id: "woodworking", name: "Woodworking", wiki: "Woodworking", category: "hobbies", emoji: "🪵" },
  { id: "fly-fishing", name: "Fly fishing", wiki: "Fly_fishing", category: "hobbies", emoji: "🎣" },
  { id: "bikepacking", name: "Bikepacking", wiki: "Bikepacking", category: "hobbies", emoji: "🚴" },
  { id: "vinyl-collecting", name: "Record collecting", wiki: "Record_collecting", category: "hobbies", emoji: "💿" },

  // --- tech ---
  { id: "iphone", name: "iPhone", wiki: "IPhone", category: "tech", emoji: "📱" },
  { id: "linux", name: "Linux", wiki: "Linux", category: "tech", emoji: "🐧" },
  { id: "arch-linux", name: "Arch Linux", wiki: "Arch_Linux", category: "tech", emoji: "🐧" },
  { id: "nixos", name: "NixOS", wiki: "NixOS", category: "tech", emoji: "❄️" },
  { id: "rust-lang", name: "Rust (programming language)", wiki: "Rust_(programming_language)", category: "tech", emoji: "🦀" },
  { id: "javascript", name: "JavaScript", wiki: "JavaScript", category: "tech", emoji: "🟨" },
  { id: "haskell", name: "Haskell", wiki: "Haskell", category: "tech", emoji: "λ" },
  { id: "vim", name: "Vim (text editor)", wiki: "Vim_(text_editor)", category: "tech", emoji: "📝" },
  { id: "emacs", name: "Emacs", wiki: "Emacs", category: "tech", emoji: "📝" },
  { id: "chatgpt", name: "ChatGPT", wiki: "ChatGPT", category: "tech", emoji: "🤖" },
  { id: "windows", name: "Microsoft Windows", wiki: "Microsoft_Windows", category: "tech", emoji: "🪟" },
  { id: "android", name: "Android (operating system)", wiki: "Android_(operating_system)", category: "tech", emoji: "🤖" },
  { id: "macos", name: "macOS", wiki: "MacOS", category: "tech", emoji: "💻" },
  { id: "chrome", name: "Google Chrome", wiki: "Google_Chrome", category: "tech", emoji: "🌐" },
  { id: "photoshop", name: "Adobe Photoshop", wiki: "Adobe_Photoshop", category: "tech", emoji: "🎨" },
  { id: "slack", name: "Slack", wiki: "Slack_(software)", category: "tech", emoji: "💬" },
  { id: "zoom", name: "Zoom", wiki: "Zoom_(software)", category: "tech", emoji: "📹" },
  { id: "elixir", name: "Elixir (programming language)", wiki: "Elixir_(programming_language)", category: "tech", emoji: "💧" },
  { id: "ocaml", name: "OCaml", wiki: "OCaml", category: "tech", emoji: "🐫" },
  { id: "zig", name: "Zig (programming language)", wiki: "Zig_(programming_language)", category: "tech", emoji: "⚡" },
  { id: "neovim", name: "Neovim", wiki: "Neovim", category: "tech", emoji: "📝" },
  { id: "tmux", name: "Tmux", wiki: "Tmux", category: "tech", emoji: "🖥️" },
  { id: "freebsd", name: "FreeBSD", wiki: "FreeBSD", category: "tech", emoji: "😈" },
  { id: "clojure", name: "Clojure", wiki: "Clojure", category: "tech", emoji: "🌀" },
  { id: "erlang", name: "Erlang (programming language)", wiki: "Erlang_(programming_language)", category: "tech", emoji: "📞" },
  { id: "apl", name: "APL (programming language)", wiki: "APL_(programming_language)", category: "tech", emoji: "🔤" },

  // --- animals ---
  { id: "golden-retriever", name: "Golden Retriever", wiki: "Golden_Retriever", category: "animals", emoji: "🐕" },
  { id: "shiba-inu", name: "Shiba Inu", wiki: "Shiba_Inu", category: "animals", emoji: "🐕" },
  { id: "bernedoodle", name: "Bernedoodle", wiki: "Bernedoodle", category: "animals", emoji: "🐕" },
  { id: "axolotl", name: "Axolotl", wiki: "Axolotl", category: "animals", emoji: "🦎" },
  { id: "capybara", name: "Capybara", wiki: "Capybara", category: "animals", emoji: "🐹" },
  { id: "octopus", name: "Octopus", wiki: "Octopus", category: "animals", emoji: "🐙" },
  { id: "ragdoll-cat", name: "Ragdoll", wiki: "Ragdoll", category: "animals", emoji: "🐈" },
  { id: "tardigrade", name: "Tardigrade", wiki: "Tardigrade", category: "animals", emoji: "🦠" },
  { id: "cat", name: "Cat", wiki: "Cat", category: "animals", emoji: "🐈" },
  { id: "dog", name: "Dog", wiki: "Dog", category: "animals", emoji: "🐕" },
  { id: "horse", name: "Horse", wiki: "Horse", category: "animals", emoji: "🐎" },
  { id: "lion", name: "Lion", wiki: "Lion", category: "animals", emoji: "🦁" },
  { id: "tiger", name: "Tiger", wiki: "Tiger", category: "animals", emoji: "🐅" },
  { id: "elephant", name: "Elephant", wiki: "Elephant", category: "animals", emoji: "🐘" },
  { id: "dolphin", name: "Dolphin", wiki: "Dolphin", category: "animals", emoji: "🐬" },
  { id: "fox", name: "Fox", wiki: "Fox", category: "animals", emoji: "🦊" },
  { id: "panda", name: "Giant panda", wiki: "Giant_panda", category: "animals", emoji: "🐼" },
  { id: "koala", name: "Koala", wiki: "Koala", category: "animals", emoji: "🐨" },
  { id: "penguin", name: "Penguin", wiki: "Penguin", category: "animals", emoji: "🐧" },
  { id: "corgi", name: "Pembroke Welsh Corgi", wiki: "Pembroke_Welsh_Corgi", category: "animals", emoji: "🐕" },
  { id: "dachshund", name: "Dachshund", wiki: "Dachshund", category: "animals", emoji: "🐕" },
  { id: "sphynx-cat", name: "Sphynx cat", wiki: "Sphynx_cat", category: "animals", emoji: "🐈" },
  { id: "maine-coon", name: "Maine Coon", wiki: "Maine_Coon", category: "animals", emoji: "🐈" },
  { id: "hedgehog", name: "Hedgehog", wiki: "Hedgehog", category: "animals", emoji: "🦔" },
  { id: "pangolin", name: "Pangolin", wiki: "Pangolin", category: "animals", emoji: "🦔" },
  { id: "narwhal", name: "Narwhal", wiki: "Narwhal", category: "animals", emoji: "🦄" },
  { id: "quokka", name: "Quokka", wiki: "Quokka", category: "animals", emoji: "🐹" },
  { id: "kakapo", name: "Kākāpō", wiki: "K%C4%81k%C4%81p%C5%8D", category: "animals", emoji: "🦜" },
  { id: "mantis-shrimp", name: "Mantis shrimp", wiki: "Mantis_shrimp", category: "animals", emoji: "🦐" },
];

export function itemsByCategory(category: Category | "mixed"): Item[] {
  if (category === "mixed") return ITEMS;
  return ITEMS.filter((i) => i.category === category);
}

export const CATEGORIES: { id: Category | "mixed"; label: string; emoji: string }[] = [
  { id: "mixed", label: "Mixed Bag", emoji: "🎲" },
  { id: "music", label: "Music", emoji: "🎸" },
  { id: "food", label: "Food", emoji: "🍕" },
  { id: "drinks", label: "Drinks", emoji: "☕" },
  { id: "cities", label: "Cities", emoji: "🏙️" },
  { id: "movies", label: "Movies", emoji: "🎬" },
  { id: "tv", label: "TV Shows", emoji: "📺" },
  { id: "books", label: "Books", emoji: "📚" },
  { id: "brands", label: "Brands", emoji: "🛍️" },
  { id: "hobbies", label: "Hobbies", emoji: "🧶" },
  { id: "tech", label: "Tech", emoji: "💻" },
  { id: "animals", label: "Animals", emoji: "🐙" },
];
