import type { Category, Item } from "./types";

// Curated bank. `wiki` is the exact Wikipedia article title (URL-encoded by the API client).
// Underscores are fine; the REST API accepts them.
// Every slug has been verified to return >0 pageviews from the Wikimedia API.
export const ITEMS: Item[] = [
  // --- music ---
  { id: "taylor-swift", name: "Taylor Swift", wiki: "Taylor_Swift", category: "music", emoji: "🎤" },
  { id: "the-beatles", name: "The Beatles", wiki: "The_Beatles", category: "music", emoji: "🎸" },
  { id: "drake", name: "Drake", wiki: "Drake_(musician)", category: "music", emoji: "🎤" },
  { id: "billie-eilish", name: "Billie Eilish", wiki: "Billie_Eilish", category: "music", emoji: "🎤" },
  { id: "beyonce", name: "Beyoncé", wiki: "Beyonc%C3%A9", category: "music", emoji: "🎤" },
  { id: "bad-bunny", name: "Bad Bunny", wiki: "Bad_Bunny", category: "music", emoji: "🎤" },
  { id: "bts", name: "BTS", wiki: "BTS", category: "music", emoji: "🎤" },
  { id: "olivia-rodrigo", name: "Olivia Rodrigo", wiki: "Olivia_Rodrigo", category: "music", emoji: "🎤" },
  { id: "harry-styles", name: "Harry Styles", wiki: "Harry_Styles", category: "music", emoji: "🎤" },
  { id: "ed-sheeran", name: "Ed Sheeran", wiki: "Ed_Sheeran", category: "music", emoji: "🎸" },
  { id: "adele", name: "Adele", wiki: "Adele", category: "music", emoji: "🎤" },
  { id: "the-weeknd", name: "The Weeknd", wiki: "The_Weeknd", category: "music", emoji: "🎤" },
  { id: "bob-dylan", name: "Bob Dylan", wiki: "Bob_Dylan", category: "music", emoji: "🎸" },
  { id: "david-bowie", name: "David Bowie", wiki: "David_Bowie", category: "music", emoji: "🎤" },
  { id: "pink-floyd", name: "Pink Floyd", wiki: "Pink_Floyd", category: "music", emoji: "🎸" },
  { id: "nirvana", name: "Nirvana", wiki: "Nirvana_(band)", category: "music", emoji: "🎸" },
  { id: "queen", name: "Queen", wiki: "Queen_(band)", category: "music", emoji: "🎸" },
  { id: "phoebe-bridgers", name: "Phoebe Bridgers", wiki: "Phoebe_Bridgers", category: "music", emoji: "🎤" },
  { id: "mitski", name: "Mitski", wiki: "Mitski", category: "music", emoji: "🎤" },
  { id: "japanese-breakfast", name: "Japanese Breakfast", wiki: "Japanese_Breakfast", category: "music", emoji: "🎤" },
  { id: "alvvays", name: "Alvvays", wiki: "Alvvays", category: "music", emoji: "🎸" },
  { id: "big-thief", name: "Big Thief", wiki: "Big_Thief", category: "music", emoji: "🎸" },
  { id: "bon-iver", name: "Bon Iver", wiki: "Bon_Iver", category: "music", emoji: "🎸" },
  { id: "vampire-weekend", name: "Vampire Weekend", wiki: "Vampire_Weekend", category: "music", emoji: "🎸" },
  { id: "arcade-fire", name: "Arcade Fire", wiki: "Arcade_Fire", category: "music", emoji: "🎸" },
  { id: "radiohead", name: "Radiohead", wiki: "Radiohead", category: "music", emoji: "🎸" },
  { id: "fleetwood-mac", name: "Fleetwood Mac", wiki: "Fleetwood_Mac", category: "music", emoji: "🎸" },
  { id: "kanye-west", name: "Kanye West", wiki: "Kanye_West", category: "music", emoji: "🎤" },
  { id: "frank-ocean", name: "Frank Ocean", wiki: "Frank_Ocean", category: "music", emoji: "🎤" },
  { id: "tyler-the-creator", name: "Tyler, the Creator", wiki: "Tyler,_the_Creator", category: "music", emoji: "🎤" },
  { id: "king-gizzard", name: "King Gizzard & the Lizard Wizard", wiki: "King_Gizzard_%26_the_Lizard_Wizard", category: "music", emoji: "🎸" },
  { id: "weyes-blood", name: "Weyes Blood", wiki: "Weyes_Blood", category: "music", emoji: "🎤" },
  { id: "sufjan-stevens", name: "Sufjan Stevens", wiki: "Sufjan_Stevens", category: "music", emoji: "🎸" },
  { id: "soccer-mommy", name: "Soccer Mommy", wiki: "Soccer_Mommy", category: "music", emoji: "🎸" },
  { id: "snail-mail", name: "Snail Mail", wiki: "Snail_Mail_(musician)", category: "music", emoji: "🎤" },
  { id: "faye-webster", name: "Faye Webster", wiki: "Faye_Webster", category: "music", emoji: "🎤" },
  { id: "black-country-new-road", name: "Black Country, New Road", wiki: "Black_Country,_New_Road", category: "music", emoji: "🎸" },
  { id: "caroline-polachek", name: "Caroline Polachek", wiki: "Caroline_Polachek", category: "music", emoji: "🎤" },
  { id: "cocteau-twins", name: "Cocteau Twins", wiki: "Cocteau_Twins", category: "music", emoji: "🎸" },
  { id: "my-bloody-valentine", name: "My Bloody Valentine", wiki: "My_Bloody_Valentine_(band)", category: "music", emoji: "🎸" },
  { id: "slowdive", name: "Slowdive", wiki: "Slowdive", category: "music", emoji: "🎸" },
  { id: "beach-house", name: "Beach House", wiki: "Beach_House", category: "music", emoji: "🎸" },
  { id: "mac-demarco", name: "Mac DeMarco", wiki: "Mac_DeMarco", category: "music", emoji: "🎸" },
  { id: "tame-impala", name: "Tame Impala", wiki: "Tame_Impala", category: "music", emoji: "🎸" },
  { id: "father-john-misty", name: "Father John Misty", wiki: "Father_John_Misty", category: "music", emoji: "🎸" },
  { id: "st-vincent", name: "St. Vincent", wiki: "St._Vincent_(musician)", category: "music", emoji: "🎸" },
  { id: "daft-punk", name: "Daft Punk", wiki: "Daft_Punk", category: "music", emoji: "🎛️" },
  { id: "aphex-twin", name: "Aphex Twin", wiki: "Aphex_Twin", category: "music", emoji: "🎛️" },
  { id: "boards-of-canada", name: "Boards of Canada", wiki: "Boards_of_Canada", category: "music", emoji: "🎛️" },
  { id: "justin-bieber", name: "Justin Bieber", wiki: "Justin_Bieber", category: "music", emoji: "🎤" },
  { id: "david-guetta", name: "David Guetta", wiki: "David_Guetta", category: "music", emoji: "🎛️" },
  { id: "pitbull", name: "Pitbull", wiki: "Pitbull_(rapper)", category: "music", emoji: "🎤" },
  { id: "chris-brown", name: "Chris Brown", wiki: "Chris_Brown", category: "music", emoji: "🎤" },
  { id: "olivia-dean", name: "Olivia Dean", wiki: "Olivia_Dean", category: "music", emoji: "🎤" },
  { id: "linkin-park", name: "Linkin Park", wiki: "Linkin_Park", category: "music", emoji: "🎸" },
  { id: "shawn-mendes", name: "Shawn Mendes", wiki: "Shawn_Mendes", category: "music", emoji: "🎤" },
  { id: "fuerza-regida", name: "Fuerza Regida", wiki: "Fuerza_Regida", category: "music", emoji: "🎸" },
  { id: "one-direction", name: "One Direction", wiki: "One_Direction", category: "music", emoji: "🎸" },
  { id: "daniel-caesar", name: "Daniel Caesar", wiki: "Daniel_Caesar", category: "music", emoji: "🎤" },
  { id: "tems", name: "Tems", wiki: "Tems", category: "music", emoji: "🎤" },
  { id: "p-nk", name: "P!nk", wiki: "Pink_(singer)", category: "music", emoji: "🎤" },
  { id: "benson-boone", name: "Benson Boone", wiki: "Benson_Boone", category: "music", emoji: "🎤" },
  { id: "feid", name: "Feid", wiki: "Feid", category: "music", emoji: "🎤" },
  { id: "mariah-carey", name: "Mariah Carey", wiki: "Mariah_Carey", category: "music", emoji: "🎤" },
  { id: "jason-derulo", name: "Jason Derulo", wiki: "Jason_Derulo", category: "music", emoji: "🎤" },
  { id: "noah-kahan", name: "Noah Kahan", wiki: "Noah_Kahan", category: "music", emoji: "🎤" },
  { id: "oasis", name: "Oasis", wiki: "Oasis_(band)", category: "music", emoji: "🎸" },
  { id: "the-cranberries", name: "The Cranberries", wiki: "The_Cranberries", category: "music", emoji: "🎸" },
  { id: "lil-baby", name: "Lil Baby", wiki: "Lil_Baby", category: "music", emoji: "🎤" },
  { id: "bee-gees", name: "Bee Gees", wiki: "Bee_Gees", category: "music", emoji: "🎸" },
  { id: "neton-vega", name: "Neton Vega", wiki: "Net%C3%B3n_Vega", category: "music", emoji: "🎤" },
  { id: "ava-max", name: "Ava Max", wiki: "Ava_Max", category: "music", emoji: "🎤" },
  { id: "giveon", name: "GIVĒON", wiki: "Giveon", category: "music", emoji: "🎤" },
  { id: "malcolm-todd", name: "Malcolm Todd", wiki: "Malcolm_Todd_(musician)", category: "music", emoji: "🎤" },
  { id: "plan-b", name: "Plan B", wiki: "Plan_B_(duo)", category: "music", emoji: "🎸" },
  { id: "tainy", name: "Tainy", wiki: "Tainy", category: "music", emoji: "🎛️" },
  { id: "eagles", name: "Eagles", wiki: "Eagles_(band)", category: "music", emoji: "🎸" },
  { id: "mohit-chauhan", name: "Mohit Chauhan", wiki: "Mohit_Chauhan", category: "music", emoji: "🎤" },
  { id: "steve-lacy", name: "Steve Lacy", wiki: "Steve_Lacy", category: "music", emoji: "🎤" },
  { id: "chris-stapleton", name: "Chris Stapleton", wiki: "Chris_Stapleton", category: "music", emoji: "🎤" },
  { id: "tory-lanez", name: "Tory Lanez", wiki: "Tory_Lanez", category: "music", emoji: "🎤" },
  { id: "martin-garrix", name: "Martin Garrix", wiki: "Martin_Garrix", category: "music", emoji: "🎛️" },
  { id: "sexyy-red", name: "Sexyy Red", wiki: "Sexyy_Red", category: "music", emoji: "🎤" },
  { id: "mike-posner", name: "Mike Posner", wiki: "Mike_Posner", category: "music", emoji: "🎤" },
  { id: "jasmine-sandlas", name: "Jasmine Sandlas", wiki: "Jasmine_Sandlas", category: "music", emoji: "🎤" },
  { id: "meghan-trainor", name: "Meghan Trainor", wiki: "Meghan_Trainor", category: "music", emoji: "🎤" },
  { id: "vishal-dadlani", name: "Vishal Dadlani", wiki: "Vishal_Dadlani", category: "music", emoji: "🎤" },
  { id: "jessie-j", name: "Jessie J", wiki: "Jessie_J", category: "music", emoji: "🎤" },
  { id: "gabito-ballesteros", name: "Gabito Ballesteros", wiki: "Gabito_Ballesteros", category: "music", emoji: "🎤" },
  { id: "5-seconds-of-summer", name: "5 Seconds of Summer", wiki: "5_Seconds_of_Summer", category: "music", emoji: "🎸" },
  { id: "mora", name: "Mora", wiki: "Mora_(singer)", category: "music", emoji: "🎤" },
  { id: "jelly-roll", name: "Jelly Roll", wiki: "Jelly_Roll_(singer)", category: "music", emoji: "🎤" },
  { id: "roddy-ricch", name: "Roddy Ricch", wiki: "Roddy_Ricch", category: "music", emoji: "🎤" },
  { id: "dei-v", name: "Dei V", wiki: "Dei_V", category: "music", emoji: "🎤" },
  { id: "the-lumineers", name: "The Lumineers", wiki: "The_Lumineers", category: "music", emoji: "🎸" },
  { id: "stephen-sanchez", name: "Stephen Sanchez", wiki: "Stephen_Sanchez", category: "music", emoji: "🎤" },
  { id: "tulsi-kumar", name: "Tulsi Kumar", wiki: "Tulsi_Kumar", category: "music", emoji: "🎤" },
  { id: "gims", name: "GIMS", wiki: "Gims", category: "music", emoji: "🎤" },
  { id: "ceelo-green", name: "CeeLo Green", wiki: "CeeLo_Green", category: "music", emoji: "🎤" },
  { id: "karan-aujla", name: "Karan Aujla", wiki: "Karan_Aujla", category: "music", emoji: "🎤" },
  { id: "los-angeles-azules", name: "Los Ángeles Azules", wiki: "Los_%C3%81ngeles_Azules", category: "music", emoji: "🎸" },
  { id: "mon-laferte", name: "Mon Laferte", wiki: "Mon_Laferte", category: "music", emoji: "🎤" },
  { id: "t-i", name: "T.I.", wiki: "T.I.", category: "music", emoji: "🎤" },
  { id: "de-la-rose", name: "De La Rose", wiki: "De_La_Rose_(singer)", category: "music", emoji: "🎤" },
  { id: "lukas-graham", name: "Lukas Graham", wiki: "Lukas_Graham", category: "music", emoji: "🎸" },
  { id: "stromae", name: "Stromae", wiki: "Stromae", category: "music", emoji: "🎤" },
  { id: "eurythmics", name: "Eurythmics", wiki: "Eurythmics", category: "music", emoji: "🎸" },
  { id: "willow", name: "WILLOW", wiki: "Willow_Smith", category: "music", emoji: "🎤" },
  { id: "ms-lauryn-hill", name: "Ms. Lauryn Hill", wiki: "Lauryn_Hill", category: "music", emoji: "🎤" },
  { id: "gabry-ponte", name: "Gabry Ponte", wiki: "Gabry_Ponte", category: "music", emoji: "🎛️" },
  { id: "paul-mccartney", name: "Paul McCartney", wiki: "Paul_McCartney", category: "music", emoji: "🎤" },
  { id: "jatin-lalit", name: "Jatin-Lalit", wiki: "Jatin%E2%80%93Lalit", category: "music", emoji: "🎤" },
  { id: "guru-randhawa", name: "Guru Randhawa", wiki: "Guru_Randhawa", category: "music", emoji: "🎤" },
  { id: "cage-the-elephant", name: "Cage The Elephant", wiki: "Cage_the_Elephant", category: "music", emoji: "🎸" },
  { id: "taio-cruz", name: "Taio Cruz", wiki: "Taio_Cruz", category: "music", emoji: "🎤" },
  { id: "portugal-the-man", name: "Portugal. The Man", wiki: "Portugal._The_Man", category: "music", emoji: "🎸" },
  { id: "the-smashing-pumpkins", name: "The Smashing Pumpkins", wiki: "The_Smashing_Pumpkins", category: "music", emoji: "🎸" },
  { id: "nate-ruess", name: "Nate Ruess", wiki: "Nate_Ruess", category: "music", emoji: "🎤" },
  { id: "b-praak", name: "B Praak", wiki: "B_Praak", category: "music", emoji: "🎤" },
  { id: "galantis", name: "Galantis", wiki: "Galantis", category: "music", emoji: "🎛️" },
  { id: "hector-el-father", name: "Héctor \"El Father\"", wiki: "H%C3%A9ctor_el_Father", category: "music", emoji: "🎤" },
  { id: "brytiago", name: "Brytiago", wiki: "Brytiago", category: "music", emoji: "🎤" },
  { id: "esdeekid", name: "EsDeeKid", wiki: "EsDeeKid", category: "music", emoji: "🎤" },
  { id: "la-oreja-de-van-gogh", name: "La Oreja de Van Gogh", wiki: "La_Oreja_de_Van_Gogh", category: "music", emoji: "🎸" },
  { id: "sai-abhyankkar", name: "Sai Abhyankkar", wiki: "Sai_Abhyankkar", category: "music", emoji: "🎤" },
  { id: "starship", name: "Starship", wiki: "Starship_(band)", category: "music", emoji: "🎸" },
  { id: "gesaffelstein", name: "Gesaffelstein", wiki: "Gesaffelstein", category: "music", emoji: "🎤" },
  { id: "melanie-martinez", name: "Melanie Martinez", wiki: "Melanie_Martinez", category: "music", emoji: "🎤" },
  { id: "van-halen", name: "Van Halen", wiki: "Van_Halen", category: "music", emoji: "🎸" },
  { id: "lloyd", name: "Lloyd", wiki: "Lloyd_(singer)", category: "music", emoji: "🎤" },
  { id: "new-west", name: "New West", wiki: "New_West_(band)", category: "music", emoji: "🎸" },
  { id: "rudimental", name: "Rudimental", wiki: "Rudimental", category: "music", emoji: "🎸" },
  { id: "chris-isaak", name: "Chris Isaak", wiki: "Chris_Isaak", category: "music", emoji: "🎤" },
  { id: "ciara", name: "Ciara", wiki: "Ciara", category: "music", emoji: "🎤" },
  { id: "marilia-mendonca", name: "Marília Mendonça", wiki: "Mar%C3%ADlia_Mendon%C3%A7a", category: "music", emoji: "🎤" },
  { id: "jay-sean", name: "Jay Sean", wiki: "Jay_Sean", category: "music", emoji: "🎤" },
  { id: "shenseea", name: "Shenseea", wiki: "Shenseea", category: "music", emoji: "🎤" },
  { id: "jazzy", name: "Jazzy", wiki: "Jazzy_(singer)", category: "music", emoji: "🎤" },
  { id: "hombres-g", name: "Hombres G", wiki: "Hombres_G", category: "music", emoji: "🎸" },
  { id: "r3hab", name: "R3HAB", wiki: "R3hab", category: "music", emoji: "🎛️" },
  { id: "clementine-douglas", name: "Clementine Douglas", wiki: "Clementine_Douglas", category: "music", emoji: "🎤" },
  { id: "jere-klein", name: "Jere Klein", wiki: "Jere_Klein", category: "music", emoji: "🎤" },
  { id: "luke-bryan", name: "Luke Bryan", wiki: "Luke_Bryan", category: "music", emoji: "🎤" },
  { id: "oliver-tree", name: "Oliver Tree", wiki: "Oliver_Tree", category: "music", emoji: "🎤" },
  { id: "the-magician", name: "The Magician", wiki: "The_Magician_(musician)", category: "music", emoji: "🎛️" },
  { id: "m", name: "MØ", wiki: "M%C3%98", category: "music", emoji: "🎤" },
  { id: "070-shake", name: "070 Shake", wiki: "070_Shake", category: "music", emoji: "🎤" },
  { id: "ilaiyaraaja", name: "Ilaiyaraaja", wiki: "Ilaiyaraaja", category: "music", emoji: "🎤" },
  { id: "soundgarden", name: "Soundgarden", wiki: "Soundgarden", category: "music", emoji: "🎸" },
  { id: "the-rare-occasions", name: "The Rare Occasions", wiki: "The_Rare_Occasions", category: "music", emoji: "🎸" },
  { id: "andy-grammer", name: "Andy Grammer", wiki: "Andy_Grammer", category: "music", emoji: "🎤" },
  { id: "pet-shop-boys", name: "Pet Shop Boys", wiki: "Pet_Shop_Boys", category: "music", emoji: "🎸" },
  { id: "naresh-iyer", name: "Naresh Iyer", wiki: "Naresh_Iyer", category: "music", emoji: "🎤" },
  { id: "coi-leray", name: "Coi Leray", wiki: "Coi_Leray", category: "music", emoji: "🎤" },
  { id: "intocable", name: "Intocable", wiki: "Intocable", category: "music", emoji: "🎸" },
  { id: "third-eye-blind", name: "Third Eye Blind", wiki: "Third_Eye_Blind", category: "music", emoji: "🎸" },
  { id: "dan-shay", name: "Dan + Shay", wiki: "Dan_%2B_Shay", category: "music", emoji: "🎸" },
  { id: "strawberry-guy", name: "Strawberry Guy", wiki: "Strawberry_Guy", category: "music", emoji: "🎤" },
  { id: "alanis-morissette", name: "Alanis Morissette", wiki: "Alanis_Morissette", category: "music", emoji: "🎤" },
  { id: "cutting-crew", name: "Cutting Crew", wiki: "Cutting_Crew", category: "music", emoji: "🎸" },
  { id: "staind", name: "Staind", wiki: "Staind", category: "music", emoji: "🎸" },
  { id: "pierce-the-veil", name: "Pierce The Veil", wiki: "Pierce_the_Veil", category: "music", emoji: "🎸" },
  { id: "elevation-worship", name: "Elevation Worship", wiki: "Elevation_Worship", category: "music", emoji: "🎸" },
  { id: "genesis", name: "Genesis", wiki: "Genesis_(band)", category: "music", emoji: "🎸" },
  { id: "spandau-ballet", name: "Spandau Ballet", wiki: "Spandau_Ballet", category: "music", emoji: "🎸" },
  { id: "iann-dior", name: "iann dior", wiki: "Iann_Dior", category: "music", emoji: "🎤" },
  { id: "missy-elliott", name: "Missy Elliott", wiki: "Missy_Elliott", category: "music", emoji: "🎤" },
  { id: "joao-gomes", name: "João Gomes", wiki: "Jo%C3%A3o_Gomes_(singer)", category: "music", emoji: "🎤" },
  { id: "otis-redding", name: "Otis Redding", wiki: "Otis_Redding", category: "music", emoji: "🎤" },
  { id: "the-temptations", name: "The Temptations", wiki: "The_Temptations", category: "music", emoji: "🎸" },
  { id: "d-o-d", name: "D.O.D", wiki: "D.O.D._(DJ)", category: "music", emoji: "🎛️" },
  { id: "arko", name: "Arko", wiki: "Arko_Pravo_Mukherjee", category: "music", emoji: "🎤" },
  { id: "mc-pedrinho", name: "Mc Pedrinho", wiki: "MC_Pedrinho", category: "music", emoji: "🎤" },
  { id: "nina-simone", name: "Nina Simone", wiki: "Nina_Simone", category: "music", emoji: "🎤" },
  { id: "sujatha", name: "Sujatha", wiki: "Sujatha_Mohan", category: "music", emoji: "🎤" },
  { id: "nas", name: "Nas", wiki: "Nas", category: "music", emoji: "🎤" },
  { id: "dasha", name: "Dasha", wiki: "Dasha_(singer)", category: "music", emoji: "🎤" },
  { id: "kevin-gates", name: "Kevin Gates", wiki: "Kevin_Gates", category: "music", emoji: "🎤" },
  { id: "the-cars", name: "The Cars", wiki: "The_Cars", category: "music", emoji: "🎸" },
  { id: "gopi-sundar", name: "Gopi Sundar", wiki: "Gopi_Sundar", category: "music", emoji: "🎤" },
  { id: "riton", name: "Riton", wiki: "Riton_(musician)", category: "music", emoji: "🎛️" },
  { id: "kaytranada", name: "KAYTRANADA", wiki: "Kaytranada", category: "music", emoji: "🎛️" },
  { id: "vacations", name: "Vacations", wiki: "Vacations_(band)", category: "music", emoji: "🎸" },
  { id: "royel-otis", name: "Royel Otis", wiki: "Royel_Otis", category: "music", emoji: "🎸" },
  { id: "young-the-giant", name: "Young the Giant", wiki: "Young_the_Giant", category: "music", emoji: "🎸" },
  { id: "flow-g", name: "Flow G", wiki: "Flow_G", category: "music", emoji: "🎤" },
  { id: "dread-mar-i", name: "Dread Mar I", wiki: "Dread_Mar_I", category: "music", emoji: "🎤" },
  { id: "loud-luxury", name: "Loud Luxury", wiki: "Loud_Luxury", category: "music", emoji: "🎸" },
  { id: "marta-sanchez", name: "Marta Sánchez", wiki: "Marta_S%C3%A1nchez", category: "music", emoji: "🎤" },
  { id: "tiakola", name: "Tiakola", wiki: "Tiakola", category: "music", emoji: "🎤" },
  { id: "dexter-and-the-moonrocks", name: "Dexter and The Moonrocks", wiki: "Dexter_and_the_Moonrocks", category: "music", emoji: "🎸" },
  { id: "r-k-m-and-ken-y", name: "R.K.M & Ken-Y", wiki: "R.K.M_%26_Ken-Y", category: "music", emoji: "🎸" },
  { id: "leon-larregui", name: "León Larregui", wiki: "Le%C3%B3n_Larregui", category: "music", emoji: "🎤" },
  { id: "kahitna", name: "Kahitna", wiki: "Kahitna", category: "music", emoji: "🎸" },
  { id: "shinedown", name: "Shinedown", wiki: "Shinedown", category: "music", emoji: "🎸" },
  { id: "jp-cooper", name: "JP Cooper", wiki: "JP_Cooper", category: "music", emoji: "🎤" },
  { id: "loreen", name: "Loreen", wiki: "Loreen", category: "music", emoji: "🎤" },
  { id: "sky-rompiendo", name: "Sky Rompiendo", wiki: "Sky_Rompiendo", category: "music", emoji: "🎤" },
  { id: "oh-wonder", name: "Oh Wonder", wiki: "Oh_Wonder", category: "music", emoji: "🎸" },
  { id: "commodores", name: "Commodores", wiki: "Commodores", category: "music", emoji: "🎸" },
  { id: "zeze-di-camargo-and-luciano", name: "Zezé Di Camargo & Luciano", wiki: "Zez%C3%A9_Di_Camargo_%26_Luciano", category: "music", emoji: "🎸" },
  { id: "europe", name: "Europe", wiki: "Europe_(band)", category: "music", emoji: "🎸" },
  { id: "a-touch-of-class", name: "A Touch Of Class", wiki: "A_Touch_of_Class_(group)", category: "music", emoji: "🎸" },
  { id: "majestic", name: "Majestic", wiki: "Majestic_(musician)", category: "music", emoji: "🎤" },
  { id: "damian-marley", name: "Damian Marley", wiki: "Damian_Marley", category: "music", emoji: "🎤" },
  { id: "wallows", name: "Wallows", wiki: "Wallows", category: "music", emoji: "🎸" },
  { id: "dexys-midnight-runners", name: "Dexys Midnight Runners", wiki: "Dexys_Midnight_Runners", category: "music", emoji: "🎸" },
  { id: "the-proclaimers", name: "The Proclaimers", wiki: "The_Proclaimers", category: "music", emoji: "🎸" },
  { id: "player", name: "Player", wiki: "Player_(band)", category: "music", emoji: "🎸" },
  { id: "mc-kevin", name: "Mc Kevin", wiki: "MC_Kevin", category: "music", emoji: "🎤" },
  { id: "sandro-cavazza", name: "Sandro Cavazza", wiki: "Sandro_Cavazza", category: "music", emoji: "🎤" },
  { id: "hippie-sabotage", name: "Hippie Sabotage", wiki: "Hippie_Sabotage", category: "music", emoji: "🎸" },
  { id: "sofiya-nzau", name: "Sofiya Nzau", wiki: "Sofiya_Nzau", category: "music", emoji: "🎤" },
  { id: "why-don-t-we", name: "Why Don't We", wiki: "Why_Don't_We", category: "music", emoji: "🎸" },
  { id: "shalmali-kholgade", name: "Shalmali Kholgade", wiki: "Shalmali_Kholgade", category: "music", emoji: "🎤" },
  { id: "charly-black", name: "Charly Black", wiki: "Charly_Black", category: "music", emoji: "🎤" },
  { id: "baby-gang", name: "Baby Gang", wiki: "Baby_Gang", category: "music", emoji: "🎤" },
  { id: "vengaboys", name: "Vengaboys", wiki: "Vengaboys", category: "music", emoji: "🎸" },
  { id: "chimbala", name: "Chimbala", wiki: "Chimbala", category: "music", emoji: "🎤" },
  { id: "five-finger-death-punch", name: "Five Finger Death Punch", wiki: "Five_Finger_Death_Punch", category: "music", emoji: "🎸" },
  { id: "42-dugg", name: "42 Dugg", wiki: "42_Dugg", category: "music", emoji: "🎤" },
  { id: "ebru-gundes", name: "Ebru Gündeş", wiki: "Ebru_G%C3%BCnde%C5%9F", category: "music", emoji: "🎤" },
  { id: "toni-braxton", name: "Toni Braxton", wiki: "Toni_Braxton", category: "music", emoji: "🎤" },
  { id: "mariah-the-scientist", name: "Mariah the Scientist", wiki: "Mariah_the_Scientist", category: "music", emoji: "🎤" },
  { id: "amanda-miguel", name: "Amanda Miguel", wiki: "Amanda_Miguel", category: "music", emoji: "🎤" },
  { id: "gurinder-gill", name: "Gurinder Gill", wiki: "Gurinder_Gill", category: "music", emoji: "🎤" },
  { id: "djavan", name: "Djavan", wiki: "Djavan", category: "music", emoji: "🎤" },
  { id: "camelphat", name: "CamelPhat", wiki: "CamelPhat", category: "music", emoji: "🎸" },
  { id: "guaynaa", name: "Guaynaa", wiki: "Guaynaa", category: "music", emoji: "🎤" },
  { id: "bossman-dlow", name: "BossMan Dlow", wiki: "BossMan_Dlow", category: "music", emoji: "🎤" },
  { id: "bjork", name: "Björk", wiki: "Bj%C3%B6rk", category: "music", emoji: "🎤" },
  { id: "sanjith-hegde", name: "Sanjith Hegde", wiki: "Sanjith_Hegde", category: "music", emoji: "🎤" },
  { id: "dilsinho", name: "Dilsinho", wiki: "Dilsinho", category: "music", emoji: "🎤" },
  { id: "lucenzo", name: "Lucenzo", wiki: "Lucenzo", category: "music", emoji: "🎤" },
  { id: "israel-kamakawiwo-ole", name: "Israel Kamakawiwo'ole", wiki: "Israel_Kamakawiwo%CA%BBole", category: "music", emoji: "🎤" },
  { id: "rupert-holmes", name: "Rupert Holmes", wiki: "Rupert_Holmes", category: "music", emoji: "🎤" },
  { id: "up-dharma-down", name: "Up Dharma Down", wiki: "UDD_(band)", category: "music", emoji: "🎸" },
  { id: "roberto-carlos", name: "Roberto Carlos", wiki: "Roberto_Carlos_(singer)", category: "music", emoji: "🎤" },
  { id: "abhay-jodhpurkar", name: "Abhay Jodhpurkar", wiki: "Abhay_Jodhpurkar", category: "music", emoji: "🎤" },
  { id: "noah", name: "Noah", wiki: "Noah_(band)", category: "music", emoji: "🎸" },
  { id: "the-paper-kites", name: "The Paper Kites", wiki: "The_Paper_Kites", category: "music", emoji: "🎸" },
  { id: "dynoro", name: "Dynoro", wiki: "Dynoro", category: "music", emoji: "🎛️" },
  { id: "twista", name: "Twista", wiki: "Twista", category: "music", emoji: "🎤" },
  { id: "snoh-aalegra", name: "Snoh Aalegra", wiki: "Snoh_Aalegra", category: "music", emoji: "🎤" },
  { id: "sleepy-hallow", name: "Sleepy Hallow", wiki: "Sleepy_Hallow", category: "music", emoji: "🎤" },
  { id: "tinlicker", name: "Tinlicker", wiki: "Tinlicker", category: "music", emoji: "🎸" },
  { id: "dhee", name: "Dhee", wiki: "Dhee_(singer)", category: "music", emoji: "🎤" },
  { id: "baby-rasta-y-gringo", name: "Baby Rasta y Gringo", wiki: "Baby_Rasta_%26_Gringo", category: "music", emoji: "🎸" },
  { id: "the-la-s", name: "The La's", wiki: "The_La's", category: "music", emoji: "🎸" },

  // --- food ---
  { id: "pizza", name: "Pizza", wiki: "Pizza", category: "food", emoji: "🍕" },
  { id: "sushi", name: "Sushi", wiki: "Sushi", category: "food", emoji: "🍣" },
  { id: "ramen", name: "Ramen", wiki: "Ramen", category: "food", emoji: "🍜" },
  { id: "pho", name: "Phở", wiki: "Pho", category: "food", emoji: "🍜" },
  { id: "kimchi", name: "Kimchi", wiki: "Kimchi", category: "food", emoji: "🥬" },
  { id: "natto", name: "Nattō", wiki: "Natt%C5%8D", category: "food", emoji: "🫘" },
  { id: "kombucha", name: "Kombucha", wiki: "Kombucha", category: "food", emoji: "🍵" },
  { id: "avocado-toast", name: "Avocado toast", wiki: "Avocado_toast", category: "food", emoji: "🥑" },
  { id: "burger", name: "Hamburger", wiki: "Hamburger", category: "food", emoji: "🍔" },
  { id: "tacos", name: "Taco", wiki: "Taco", category: "food", emoji: "🌮" },
  { id: "poke", name: "Poke", wiki: "Poke_(dish)", category: "food", emoji: "🐟" },
  { id: "ceviche", name: "Ceviche", wiki: "Ceviche", category: "food", emoji: "🐟" },
  { id: "shakshuka", name: "Shakshouka", wiki: "Shakshouka", category: "food", emoji: "🍳" },
  { id: "miso-soup", name: "Miso soup", wiki: "Miso_soup", category: "food", emoji: "🍜" },
  { id: "kouign-amann", name: "Kouign-amann", wiki: "Kouign-amann", category: "food", emoji: "🥐" },
  { id: "croissant", name: "Croissant", wiki: "Croissant", category: "food", emoji: "🥐" },
  { id: "biryani", name: "Biryani", wiki: "Biryani", category: "food", emoji: "🍛" },
  { id: "butter-chicken", name: "Butter chicken", wiki: "Butter_chicken", category: "food", emoji: "🍛" },
  { id: "dosa", name: "Dosa", wiki: "Dosa", category: "food", emoji: "🥞" },
  { id: "carbonara", name: "Carbonara", wiki: "Carbonara", category: "food", emoji: "🍝" },
  { id: "lasagna", name: "Lasagna", wiki: "Lasagna", category: "food", emoji: "🍝" },
  { id: "risotto", name: "Risotto", wiki: "Risotto", category: "food", emoji: "🍚" },
  { id: "cacio-e-pepe", name: "Cacio e pepe", wiki: "Cacio_e_pepe", category: "food", emoji: "🍝" },
  { id: "mole", name: "Mole", wiki: "Mole_(sauce)", category: "food", emoji: "🌶️" },
  { id: "pupusa", name: "Pupusa", wiki: "Pupusa", category: "food", emoji: "🫓" },
  { id: "arepa", name: "Arepa", wiki: "Arepa", category: "food", emoji: "🫓" },
  { id: "bibimbap", name: "Bibimbap", wiki: "Bibimbap", category: "food", emoji: "🍲" },
  { id: "banh-mi", name: "Bánh mì", wiki: "B%C3%A1nh_m%C3%AC", category: "food", emoji: "🥖" },
  { id: "laksa", name: "Laksa", wiki: "Laksa", category: "food", emoji: "🍜" },
  { id: "pad-thai", name: "Pad thai", wiki: "Pad_thai", category: "food", emoji: "🍜" },
  { id: "dim-sum", name: "Dim sum", wiki: "Dim_sum", category: "food", emoji: "🥟" },
  { id: "takoyaki", name: "Takoyaki", wiki: "Takoyaki", category: "food", emoji: "🐙" },
  { id: "tonkatsu", name: "Tonkatsu", wiki: "Tonkatsu", category: "food", emoji: "🍱" },
  { id: "sourdough", name: "Sourdough", wiki: "Sourdough", category: "food", emoji: "🍞" },
  { id: "tahini", name: "Tahini", wiki: "Tahini", category: "food", emoji: "🥣" },
  { id: "french-fries", name: "French fries", wiki: "French_fries", category: "food", emoji: "🍟" },
  { id: "fried-chicken", name: "Fried chicken", wiki: "Fried_chicken", category: "food", emoji: "🍗" },
  { id: "durian", name: "Durian", wiki: "Durian", category: "food", emoji: "🥥" },

  // --- cities ---
  { id: "new-york", name: "New York City", wiki: "New_York_City", category: "cities", emoji: "🗽" },
  { id: "paris", name: "Paris", wiki: "Paris", category: "cities", emoji: "🗼" },
  { id: "tokyo", name: "Tokyo", wiki: "Tokyo", category: "cities", emoji: "🗾" },
  { id: "london", name: "London", wiki: "London", category: "cities", emoji: "🎡" },
  { id: "berlin", name: "Berlin", wiki: "Berlin", category: "cities", emoji: "🍻" },
  { id: "portland", name: "Portland, Oregon", wiki: "Portland,_Oregon", category: "cities", emoji: "🌲" },
  { id: "austin", name: "Austin, Texas", wiki: "Austin,_Texas", category: "cities", emoji: "🤠" },
  { id: "asheville", name: "Asheville, North Carolina", wiki: "Asheville,_North_Carolina", category: "cities", emoji: "🏔️" },
  { id: "marfa", name: "Marfa, Texas", wiki: "Marfa,_Texas", category: "cities", emoji: "🎨" },
  { id: "reykjavik", name: "Reykjavík", wiki: "Reykjav%C3%ADk", category: "cities", emoji: "❄️" },
  { id: "lisbon", name: "Lisbon", wiki: "Lisbon", category: "cities", emoji: "🌊" },
  { id: "copenhagen", name: "Copenhagen", wiki: "Copenhagen", category: "cities", emoji: "🚲" },
  { id: "tulum", name: "Tulum", wiki: "Tulum", category: "cities", emoji: "🌴" },
  { id: "oaxaca", name: "Oaxaca City", wiki: "Oaxaca_City", category: "cities", emoji: "🌶️" },
  { id: "los-angeles", name: "Los Angeles", wiki: "Los_Angeles", category: "cities", emoji: "🌴" },
  { id: "chicago", name: "Chicago", wiki: "Chicago", category: "cities", emoji: "🏙️" },
  { id: "san-francisco", name: "San Francisco", wiki: "San_Francisco", category: "cities", emoji: "🌉" },
  { id: "miami", name: "Miami", wiki: "Miami", category: "cities", emoji: "🌴" },
  { id: "las-vegas", name: "Las Vegas", wiki: "Las_Vegas", category: "cities", emoji: "🎰" },
  { id: "seattle", name: "Seattle", wiki: "Seattle", category: "cities", emoji: "🏔️" },
  { id: "boston", name: "Boston", wiki: "Boston", category: "cities", emoji: "🦞" },
  { id: "toronto", name: "Toronto", wiki: "Toronto", category: "cities", emoji: "🍁" },
  { id: "mexico-city", name: "Mexico City", wiki: "Mexico_City", category: "cities", emoji: "🌮" },
  { id: "rome", name: "Rome", wiki: "Rome", category: "cities", emoji: "🏛️" },
  { id: "barcelona", name: "Barcelona", wiki: "Barcelona", category: "cities", emoji: "🏖️" },
  { id: "amsterdam", name: "Amsterdam", wiki: "Amsterdam", category: "cities", emoji: "🚲" },
  { id: "bangkok", name: "Bangkok", wiki: "Bangkok", category: "cities", emoji: "🛺" },
  { id: "dubai", name: "Dubai", wiki: "Dubai", category: "cities", emoji: "🏗️" },
  { id: "sydney", name: "Sydney", wiki: "Sydney", category: "cities", emoji: "🦘" },
  { id: "hong-kong", name: "Hong Kong", wiki: "Hong_Kong", category: "cities", emoji: "🏙️" },
  { id: "mumbai", name: "Mumbai", wiki: "Mumbai", category: "cities", emoji: "🇮🇳" },
  { id: "porto", name: "Porto", wiki: "Porto", category: "cities", emoji: "🍷" },
  { id: "cape-town", name: "Cape Town", wiki: "Cape_Town", category: "cities", emoji: "🏔️" },
  { id: "tbilisi", name: "Tbilisi", wiki: "Tbilisi", category: "cities", emoji: "🍷" },
  { id: "tallinn", name: "Tallinn", wiki: "Tallinn", category: "cities", emoji: "🏰" },
  { id: "hanoi", name: "Hanoi", wiki: "Hanoi", category: "cities", emoji: "🥢" },
  { id: "antwerp", name: "Antwerp", wiki: "Antwerp", category: "cities", emoji: "💎" },
  { id: "joshua-tree", name: "Joshua Tree, California", wiki: "Joshua_Tree,_California", category: "cities", emoji: "🌵" },
  { id: "hudson-ny", name: "Hudson, New York", wiki: "Hudson,_New_York", category: "cities", emoji: "🏘️" },
  { id: "provincetown", name: "Provincetown, Massachusetts", wiki: "Provincetown,_Massachusetts", category: "cities", emoji: "🏖️" },

  // --- movies ---
  { id: "titanic", name: "Titanic (1997 film)", wiki: "Titanic_(1997_film)", category: "movies", emoji: "🚢" },
  { id: "avengers-endgame", name: "Avengers: Endgame", wiki: "Avengers:_Endgame", category: "movies", emoji: "🦸" },
  { id: "barbie", name: "Barbie (film)", wiki: "Barbie_(film)", category: "movies", emoji: "👱‍♀️" },
  { id: "oppenheimer", name: "Oppenheimer (film)", wiki: "Oppenheimer_(film)", category: "movies", emoji: "💥" },
  { id: "parasite", name: "Parasite (2019 film)", wiki: "Parasite_(2019_film)", category: "movies", emoji: "🎬" },
  { id: "everything-everywhere", name: "Everything Everywhere All at Once", wiki: "Everything_Everywhere_All_at_Once", category: "movies", emoji: "🥯" },
  { id: "the-lighthouse", name: "The Lighthouse (2019 film)", wiki: "The_Lighthouse_(2019_film)", category: "movies", emoji: "🦞" },
  { id: "midsommar", name: "Midsommar (film)", wiki: "Midsommar_(film)", category: "movies", emoji: "🌼" },
  { id: "moonlight", name: "Moonlight (2016 film)", wiki: "Moonlight_(2016_film)", category: "movies", emoji: "🌙" },
  { id: "the-favourite", name: "The Favourite", wiki: "The_Favourite_(2018_film)", category: "movies", emoji: "👑" },
  { id: "frances-ha", name: "Frances Ha", wiki: "Frances_Ha", category: "movies", emoji: "💃" },
  { id: "lady-bird", name: "Lady Bird (film)", wiki: "Lady_Bird_(film)", category: "movies", emoji: "🐦" },
  { id: "inception", name: "Inception", wiki: "Inception", category: "movies", emoji: "🌀" },
  { id: "the-dark-knight", name: "The Dark Knight", wiki: "The_Dark_Knight", category: "movies", emoji: "🦇" },
  { id: "avatar", name: "Avatar (2009 film)", wiki: "Avatar_(2009_film)", category: "movies", emoji: "🌌" },
  { id: "pulp-fiction", name: "Pulp Fiction", wiki: "Pulp_Fiction", category: "movies", emoji: "🔫" },
  { id: "interstellar", name: "Interstellar (film)", wiki: "Interstellar_(film)", category: "movies", emoji: "🪐" },
  { id: "the-godfather", name: "The Godfather", wiki: "The_Godfather", category: "movies", emoji: "🎩" },
  { id: "forrest-gump", name: "Forrest Gump", wiki: "Forrest_Gump", category: "movies", emoji: "🏃" },
  { id: "aftersun", name: "Aftersun", wiki: "Aftersun", category: "movies", emoji: "📼" },
  { id: "past-lives", name: "Past Lives (film)", wiki: "Past_Lives_(film)", category: "movies", emoji: "✨" },
  { id: "uncut-gems", name: "Uncut Gems", wiki: "Uncut_Gems", category: "movies", emoji: "💎" },
  { id: "burning", name: "Burning (2018 film)", wiki: "Burning_(2018_film)", category: "movies", emoji: "🔥" },
  { id: "drive-my-car", name: "Drive My Car (film)", wiki: "Drive_My_Car_(film)", category: "movies", emoji: "🚗" },
  { id: "petite-maman", name: "Petite Maman", wiki: "Petite_Maman", category: "movies", emoji: "👧" },
  { id: "first-cow", name: "First Cow", wiki: "First_Cow", category: "movies", emoji: "🐄" },
  { id: "minari", name: "Minari (film)", wiki: "Minari_(film)", category: "movies", emoji: "🌱" },
  { id: "the-power-of-the-dog", name: "The Power of the Dog (film)", wiki: "The_Power_of_the_Dog_(film)", category: "movies", emoji: "🐕" },
  { id: "nomadland", name: "Nomadland", wiki: "Nomadland", category: "movies", emoji: "🚐" },
  { id: "the-florida-project", name: "The Florida Project", wiki: "The_Florida_Project", category: "movies", emoji: "🏨" },
  // mega-mainstream blockbusters
  { id: "shawshank-redemption", name: "The Shawshank Redemption", wiki: "The_Shawshank_Redemption", category: "movies", emoji: "🔨" },
  { id: "the-matrix", name: "The Matrix", wiki: "The_Matrix", category: "movies", emoji: "🕶️" },
  { id: "fight-club", name: "Fight Club", wiki: "Fight_Club", category: "movies", emoji: "🧼" },
  { id: "lotr-fellowship", name: "The Lord of the Rings: The Fellowship of the Ring", wiki: "The_Lord_of_the_Rings:_The_Fellowship_of_the_Ring", category: "movies", emoji: "💍" },
  { id: "jurassic-park", name: "Jurassic Park", wiki: "Jurassic_Park", category: "movies", emoji: "🦖" },
  { id: "the-lion-king", name: "The Lion King", wiki: "The_Lion_King", category: "movies", emoji: "🦁" },
  { id: "gladiator", name: "Gladiator (2000 film)", wiki: "Gladiator_(2000_film)", category: "movies", emoji: "⚔️" },
  { id: "joker", name: "Joker (2019 film)", wiki: "Joker_(2019_film)", category: "movies", emoji: "🤡" },
  { id: "the-avengers", name: "The Avengers (2012 film)", wiki: "The_Avengers_(2012_film)", category: "movies", emoji: "🛡️" },
  { id: "avengers-infinity-war", name: "Avengers: Infinity War", wiki: "Avengers:_Infinity_War", category: "movies", emoji: "🧤" },
  { id: "iron-man", name: "Iron Man (2008 film)", wiki: "Iron_Man_(2008_film)", category: "movies", emoji: "🤖" },
  { id: "the-wolf-of-wall-street", name: "The Wolf of Wall Street (2013 film)", wiki: "The_Wolf_of_Wall_Street_(2013_film)", category: "movies", emoji: "💰" },
  { id: "django-unchained", name: "Django Unchained", wiki: "Django_Unchained", category: "movies", emoji: "🤠" },
  { id: "the-departed", name: "The Departed", wiki: "The_Departed", category: "movies", emoji: "🚓" },
  { id: "goodfellas", name: "Goodfellas", wiki: "Goodfellas", category: "movies", emoji: "🍝" },
  { id: "saving-private-ryan", name: "Saving Private Ryan", wiki: "Saving_Private_Ryan", category: "movies", emoji: "🪖" },
  { id: "schindlers-list", name: "Schindler's List", wiki: "Schindler's_List", category: "movies", emoji: "🕯️" },
  { id: "the-silence-of-the-lambs", name: "The Silence of the Lambs", wiki: "The_Silence_of_the_Lambs_(film)", category: "movies", emoji: "🦋" },
  { id: "se7en", name: "Se7en", wiki: "Se7en", category: "movies", emoji: "🔪" },
  { id: "terminator-2", name: "Terminator 2: Judgment Day", wiki: "Terminator_2:_Judgment_Day", category: "movies", emoji: "🦾" },
  { id: "back-to-the-future", name: "Back to the Future", wiki: "Back_to_the_Future", category: "movies", emoji: "⏰" },
  { id: "star-wars", name: "Star Wars (film)", wiki: "Star_Wars_(film)", category: "movies", emoji: "🌠" },
  { id: "the-empire-strikes-back", name: "The Empire Strikes Back", wiki: "The_Empire_Strikes_Back", category: "movies", emoji: "❄️" },
  { id: "the-prestige", name: "The Prestige (film)", wiki: "The_Prestige_(film)", category: "movies", emoji: "🪄" },
  { id: "the-green-mile", name: "The Green Mile (film)", wiki: "The_Green_Mile_(film)", category: "movies", emoji: "🟢" },
  { id: "gone-girl", name: "Gone Girl (film)", wiki: "Gone_Girl_(film)", category: "movies", emoji: "🔍" },
  { id: "shutter-island", name: "Shutter Island", wiki: "Shutter_Island_(film)", category: "movies", emoji: "🏝️" },
  { id: "guardians-of-the-galaxy", name: "Guardians of the Galaxy (film)", wiki: "Guardians_of_the_Galaxy_(film)", category: "movies", emoji: "🚀" },
  { id: "deadpool", name: "Deadpool (film)", wiki: "Deadpool_(film)", category: "movies", emoji: "🩸" },
  { id: "the-hangover", name: "The Hangover", wiki: "The_Hangover", category: "movies", emoji: "🎰" },
  { id: "inglourious-basterds", name: "Inglourious Basterds", wiki: "Inglourious_Basterds", category: "movies", emoji: "🎯" },
  { id: "mad-max-fury-road", name: "Mad Max: Fury Road", wiki: "Mad_Max:_Fury_Road", category: "movies", emoji: "🏜️" },
  // popular & widely acclaimed
  { id: "la-la-land", name: "La La Land", wiki: "La_La_Land", category: "movies", emoji: "🎹" },
  { id: "whiplash", name: "Whiplash (2014 film)", wiki: "Whiplash_(2014_film)", category: "movies", emoji: "🥁" },
  { id: "get-out", name: "Get Out", wiki: "Get_Out", category: "movies", emoji: "🫖" },
  { id: "no-country-for-old-men", name: "No Country for Old Men", wiki: "No_Country_for_Old_Men_(film)", category: "movies", emoji: "💨" },
  { id: "there-will-be-blood", name: "There Will Be Blood", wiki: "There_Will_Be_Blood", category: "movies", emoji: "🛢️" },
  { id: "black-swan", name: "Black Swan (film)", wiki: "Black_Swan_(film)", category: "movies", emoji: "🦢" },
  { id: "arrival", name: "Arrival (film)", wiki: "Arrival_(film)", category: "movies", emoji: "🛸" },
  { id: "her", name: "Her (film)", wiki: "Her_(2013_film)", category: "movies", emoji: "📱" },
  { id: "blade-runner-2049", name: "Blade Runner 2049", wiki: "Blade_Runner_2049", category: "movies", emoji: "🌆" },
  { id: "the-grand-budapest-hotel", name: "The Grand Budapest Hotel", wiki: "The_Grand_Budapest_Hotel", category: "movies", emoji: "🛎️" },
  { id: "1917", name: "1917 (2019 film)", wiki: "1917_(2019_film)", category: "movies", emoji: "🎖️" },
  { id: "knives-out", name: "Knives Out", wiki: "Knives_Out", category: "movies", emoji: "🗡️" },
  { id: "birdman", name: "Birdman (film)", wiki: "Birdman_(film)", category: "movies", emoji: "🎭" },
  { id: "12-years-a-slave", name: "12 Years a Slave (film)", wiki: "12_Years_a_Slave_(film)", category: "movies", emoji: "⛓️" },
  { id: "dunkirk", name: "Dunkirk (2017 film)", wiki: "Dunkirk_(2017_film)", category: "movies", emoji: "⛴️" },
  { id: "drive-2011", name: "Drive (2011 film)", wiki: "Drive_(2011_film)", category: "movies", emoji: "🧥" },
  { id: "500-days-of-summer", name: "500 Days of Summer", wiki: "500_Days_of_Summer", category: "movies", emoji: "💔" },
  { id: "juno", name: "Juno (film)", wiki: "Juno_(film)", category: "movies", emoji: "🤰" },
  { id: "little-miss-sunshine", name: "Little Miss Sunshine", wiki: "Little_Miss_Sunshine", category: "movies", emoji: "🌻" },
  { id: "eternal-sunshine", name: "Eternal Sunshine of the Spotless Mind", wiki: "Eternal_Sunshine_of_the_Spotless_Mind", category: "movies", emoji: "🧠" },
  { id: "memento", name: "Memento (film)", wiki: "Memento_(film)", category: "movies", emoji: "📸" },
  { id: "requiem-for-a-dream", name: "Requiem for a Dream", wiki: "Requiem_for_a_Dream", category: "movies", emoji: "💉" },
  { id: "donnie-darko", name: "Donnie Darko", wiki: "Donnie_Darko", category: "movies", emoji: "🐰" },
  { id: "trainspotting", name: "Trainspotting (film)", wiki: "Trainspotting_(film)", category: "movies", emoji: "💊" },
  { id: "american-psycho", name: "American Psycho (film)", wiki: "American_Psycho_(film)", category: "movies", emoji: "🪓" },
  { id: "prisoners", name: "Prisoners (2013 film)", wiki: "Prisoners_(2013_film)", category: "movies", emoji: "🙏" },
  { id: "nightcrawler", name: "Nightcrawler (film)", wiki: "Nightcrawler_(film)", category: "movies", emoji: "📹" },
  { id: "ex-machina", name: "Ex Machina (film)", wiki: "Ex_Machina_(film)", category: "movies", emoji: "💡" },
  { id: "moonrise-kingdom", name: "Moonrise Kingdom", wiki: "Moonrise_Kingdom", category: "movies", emoji: "🏕️" },
  { id: "the-social-network", name: "The Social Network", wiki: "The_Social_Network", category: "movies", emoji: "💻" },
  { id: "gravity", name: "Gravity (2013 film)", wiki: "Gravity_(2013_film)", category: "movies", emoji: "🛰️" },
  { id: "slumdog-millionaire", name: "Slumdog Millionaire", wiki: "Slumdog_Millionaire", category: "movies", emoji: "💵" },
  { id: "spotlight", name: "Spotlight (film)", wiki: "Spotlight_(film)", category: "movies", emoji: "📰" },
  { id: "the-truman-show", name: "The Truman Show", wiki: "The_Truman_Show", category: "movies", emoji: "⛵" },
  { id: "groundhog-day", name: "Groundhog Day (film)", wiki: "Groundhog_Day_(film)", category: "movies", emoji: "🦫" },
  // international crossovers
  { id: "amelie", name: "Amélie", wiki: "Am%C3%A9lie", category: "movies", emoji: "🍒" },
  { id: "pans-labyrinth", name: "Pan's Labyrinth", wiki: "Pan's_Labyrinth", category: "movies", emoji: "🌿" },
  { id: "city-of-god", name: "City of God (2002 film)", wiki: "City_of_God_(2002_film)", category: "movies", emoji: "🏘️" },
  { id: "oldboy", name: "Oldboy (2003 film)", wiki: "Oldboy_(2003_film)", category: "movies", emoji: "🐙" },
  { id: "spirited-away", name: "Spirited Away", wiki: "Spirited_Away", category: "movies", emoji: "🛁" },
  { id: "your-name", name: "Your Name", wiki: "Your_Name", category: "movies", emoji: "☄️" },
  // arthouse & festival darlings
  { id: "hereditary", name: "Hereditary (film)", wiki: "Hereditary_(film)", category: "movies", emoji: "🐜" },
  { id: "the-witch", name: "The Witch (2015 film)", wiki: "The_Witch_(2015_film)", category: "movies", emoji: "🐐" },
  { id: "portrait-of-a-lady-on-fire", name: "Portrait of a Lady on Fire", wiki: "Portrait_of_a_Lady_on_Fire", category: "movies", emoji: "🖼️" },
  { id: "shoplifters", name: "Shoplifters (film)", wiki: "Shoplifters_(film)", category: "movies", emoji: "🛒" },
  { id: "cold-war", name: "Cold War (2018 film)", wiki: "Cold_War_(2018_film)", category: "movies", emoji: "🎶" },
  { id: "the-worst-person-in-the-world", name: "The Worst Person in the World (film)", wiki: "The_Worst_Person_in_the_World_(film)", category: "movies", emoji: "🙂" },
  { id: "tar", name: "Tár", wiki: "T%C3%A1r", category: "movies", emoji: "🎼" },
  { id: "anatomy-of-a-fall", name: "Anatomy of a Fall", wiki: "Anatomy_of_a_Fall", category: "movies", emoji: "⚖️" },
  { id: "decision-to-leave", name: "Decision to Leave", wiki: "Decision_to_Leave", category: "movies", emoji: "🏔️" },
  { id: "the-lobster", name: "The Lobster", wiki: "The_Lobster", category: "movies", emoji: "🦐" },
  { id: "paterson", name: "Paterson (film)", wiki: "Paterson_(film)", category: "movies", emoji: "🚌" },
  { id: "a-ghost-story", name: "A Ghost Story", wiki: "A_Ghost_Story", category: "movies", emoji: "👻" },
  { id: "good-time", name: "Good Time (film)", wiki: "Good_Time_(film)", category: "movies", emoji: "🌃" },
  { id: "the-souvenir", name: "The Souvenir", wiki: "The_Souvenir", category: "movies", emoji: "🎞️" },
  { id: "columbus", name: "Columbus (2017 film)", wiki: "Columbus_(2017_film)", category: "movies", emoji: "🏛️" },
  { id: "mid90s", name: "Mid90s", wiki: "Mid90s", category: "movies", emoji: "🛹" },
  { id: "under-the-skin", name: "Under the Skin (2013 film)", wiki: "Under_the_Skin_(2013_film)", category: "movies", emoji: "👽" },
  { id: "the-master", name: "The Master (2012 film)", wiki: "The_Master_(2012_film)", category: "movies", emoji: "🌊" },
  { id: "phantom-thread", name: "Phantom Thread", wiki: "Phantom_Thread", category: "movies", emoji: "🧵" },
  { id: "inside-llewyn-davis", name: "Inside Llewyn Davis", wiki: "Inside_Llewyn_Davis", category: "movies", emoji: "🐈" },
  { id: "synecdoche-new-york", name: "Synecdoche, New York", wiki: "Synecdoche,_New_York", category: "movies", emoji: "🏚️" },
  { id: "enter-the-void", name: "Enter the Void", wiki: "Enter_the_Void", category: "movies", emoji: "💫" },
  { id: "only-lovers-left-alive", name: "Only Lovers Left Alive", wiki: "Only_Lovers_Left_Alive", category: "movies", emoji: "🧛" },
  { id: "saint-maud", name: "Saint Maud", wiki: "Saint_Maud", category: "movies", emoji: "😇" },
  { id: "we-need-to-talk-about-kevin", name: "We Need to Talk About Kevin (film)", wiki: "We_Need_to_Talk_About_Kevin_(film)", category: "movies", emoji: "🏹" },
  { id: "eo", name: "EO (film)", wiki: "EO_(film)", category: "movies", emoji: "🫏" },
  { id: "close-2022", name: "Close (2022 film)", wiki: "Close_(2022_film)", category: "movies", emoji: "🌸" },
  { id: "the-zone-of-interest", name: "The Zone of Interest (film)", wiki: "The_Zone_of_Interest_(film)", category: "movies", emoji: "🏡" },
  { id: "triangle-of-sadness", name: "Triangle of Sadness", wiki: "Triangle_of_Sadness", category: "movies", emoji: "🛥️" },
  { id: "the-banshees-of-inisherin", name: "The Banshees of Inisherin", wiki: "The_Banshees_of_Inisherin", category: "movies", emoji: "🎻" },

  // --- tv ---
  { id: "friends", name: "Friends", wiki: "Friends", category: "tv", emoji: "📺" },
  { id: "the-office", name: "The Office (American TV series)", wiki: "The_Office_(American_TV_series)", category: "tv", emoji: "📎" },
  { id: "game-of-thrones", name: "Game of Thrones", wiki: "Game_of_Thrones", category: "tv", emoji: "🐉" },
  { id: "stranger-things", name: "Stranger Things", wiki: "Stranger_Things", category: "tv", emoji: "🔦" },
  { id: "breaking-bad", name: "Breaking Bad", wiki: "Breaking_Bad", category: "tv", emoji: "🧪" },
  { id: "mad-men", name: "Mad Men", wiki: "Mad_Men", category: "tv", emoji: "🥃" },
  { id: "succession", name: "Succession (TV series)", wiki: "Succession_(TV_series)", category: "tv", emoji: "🏛️" },
  { id: "atlanta-tv", name: "Atlanta (TV series)", wiki: "Atlanta_(TV_series)", category: "tv", emoji: "🍑" },
  { id: "severance", name: "Severance (TV series)", wiki: "Severance_(TV_series)", category: "tv", emoji: "🧠" },
  { id: "the-bear", name: "The Bear (TV series)", wiki: "The_Bear_(TV_series)", category: "tv", emoji: "🐻" },
  { id: "fleabag", name: "Fleabag", wiki: "Fleabag", category: "tv", emoji: "🦊" },
  { id: "better-call-saul", name: "Better Call Saul", wiki: "Better_Call_Saul", category: "tv", emoji: "⚖️" },
  { id: "bojack-horseman", name: "BoJack Horseman", wiki: "BoJack_Horseman", category: "tv", emoji: "🐴" },
  { id: "twin-peaks", name: "Twin Peaks", wiki: "Twin_Peaks", category: "tv", emoji: "🌲" },
  { id: "the-sopranos", name: "The Sopranos", wiki: "The_Sopranos", category: "tv", emoji: "🍝" },
  { id: "curb-your-enthusiasm", name: "Curb Your Enthusiasm", wiki: "Curb_Your_Enthusiasm", category: "tv", emoji: "😤" },
  { id: "i-think-you-should-leave", name: "I Think You Should Leave with Tim Robinson", wiki: "I_Think_You_Should_Leave_with_Tim_Robinson", category: "tv", emoji: "🚪" },
  { id: "reservation-dogs", name: "Reservation Dogs", wiki: "Reservation_Dogs", category: "tv", emoji: "🐕" },
  { id: "mr-robot", name: "Mr. Robot", wiki: "Mr._Robot", category: "tv", emoji: "🤖" },
  { id: "yellowjackets", name: "Yellowjackets (TV series)", wiki: "Yellowjackets_(TV_series)", category: "tv", emoji: "🐝" },
  { id: "the-wire", name: "The Wire", wiki: "The_Wire", category: "tv", emoji: "📞" },
  { id: "lost", name: "Lost (TV series)", wiki: "Lost_(TV_series)", category: "tv", emoji: "🏝️" },
  { id: "the-mandalorian", name: "The Mandalorian", wiki: "The_Mandalorian", category: "tv", emoji: "👶" },
  { id: "bluey", name: "Bluey", wiki: "Bluey_(2018_TV_series)", category: "tv", emoji: "🐶" },

  // --- books ---
  { id: "harry-potter", name: "Harry Potter", wiki: "Harry_Potter", category: "books", emoji: "⚡" },
  { id: "the-great-gatsby", name: "The Great Gatsby", wiki: "The_Great_Gatsby", category: "books", emoji: "🥂" },
  { id: "1984-book", name: "Nineteen Eighty-Four", wiki: "Nineteen_Eighty-Four", category: "books", emoji: "👁️" },
  { id: "lotr", name: "The Lord of the Rings", wiki: "The_Lord_of_the_Rings", category: "books", emoji: "💍" },
  { id: "to-kill-a-mockingbird", name: "To Kill a Mockingbird", wiki: "To_Kill_a_Mockingbird", category: "books", emoji: "🐦" },
  { id: "the-hunger-games", name: "The Hunger Games", wiki: "The_Hunger_Games", category: "books", emoji: "🏹" },
  { id: "the-catcher-in-the-rye", name: "The Catcher in the Rye", wiki: "The_Catcher_in_the_Rye", category: "books", emoji: "🧢" },
  { id: "pride-and-prejudice", name: "Pride and Prejudice", wiki: "Pride_and_Prejudice", category: "books", emoji: "💌" },
  { id: "infinite-jest", name: "Infinite Jest", wiki: "Infinite_Jest", category: "books", emoji: "🎾" },
  { id: "normal-people", name: "Normal People (novel)", wiki: "Normal_People", category: "books", emoji: "💔" },
  { id: "my-year-of-rest", name: "My Year of Rest and Relaxation", wiki: "My_Year_of_Rest_and_Relaxation", category: "books", emoji: "💊" },
  { id: "just-kids", name: "Just Kids", wiki: "Just_Kids", category: "books", emoji: "📷" },
  { id: "crying-in-h-mart", name: "Crying in H Mart", wiki: "Crying_in_H_Mart", category: "books", emoji: "😢" },
  { id: "pachinko", name: "Pachinko (novel)", wiki: "Pachinko_(novel)", category: "books", emoji: "🎰" },
  { id: "the-secret-history", name: "The Secret History", wiki: "The_Secret_History", category: "books", emoji: "🏛️" },
  { id: "tomorrow-tomorrow", name: "Tomorrow, and Tomorrow, and Tomorrow (novel)", wiki: "Tomorrow,_and_Tomorrow,_and_Tomorrow_(novel)", category: "books", emoji: "🎮" },
  { id: "beloved", name: "Beloved (novel)", wiki: "Beloved_(novel)", category: "books", emoji: "📖" },
  { id: "the-road", name: "The Road", wiki: "The_Road", category: "books", emoji: "🛣️" },
  { id: "lincoln-in-the-bardo", name: "Lincoln in the Bardo", wiki: "Lincoln_in_the_Bardo", category: "books", emoji: "🎩" },
  { id: "a-little-life", name: "A Little Life", wiki: "A_Little_Life", category: "books", emoji: "💔" },
  { id: "atomic-habits", name: "Atomic Habits", wiki: "Atomic_Habits", category: "books", emoji: "⚛️" },
  { id: "sapiens", name: "Sapiens: A Brief History of Humankind", wiki: "Sapiens:_A_Brief_History_of_Humankind", category: "books", emoji: "🧠" },
  { id: "the-alchemist", name: "The Alchemist", wiki: "The_Alchemist_(novel)", category: "books", emoji: "🪄" },
  { id: "where-the-crawdads-sing", name: "Where the Crawdads Sing", wiki: "Where_the_Crawdads_Sing", category: "books", emoji: "🦞" },

  // --- drinks ---
  { id: "coffee", name: "Coffee", wiki: "Coffee", category: "drinks", emoji: "☕" },
  { id: "espresso", name: "Espresso", wiki: "Espresso", category: "drinks", emoji: "☕" },
  { id: "matcha", name: "Matcha", wiki: "Matcha", category: "drinks", emoji: "🍵" },
  { id: "yerba-mate", name: "Yerba mate", wiki: "Yerba_mate", category: "drinks", emoji: "🧉" },
  { id: "natural-wine", name: "Natural wine", wiki: "Natural_wine", category: "drinks", emoji: "🍷" },
  { id: "negroni", name: "Negroni", wiki: "Negroni", category: "drinks", emoji: "🍸" },
  { id: "aperol-spritz", name: "Aperol Spritz", wiki: "Spritz_Veneziano", category: "drinks", emoji: "🥂" },
  { id: "ipa", name: "India pale ale", wiki: "India_pale_ale", category: "drinks", emoji: "🍺" },
  { id: "mezcal", name: "Mezcal", wiki: "Mezcal", category: "drinks", emoji: "🌵" },
  { id: "soju", name: "Soju", wiki: "Soju", category: "drinks", emoji: "🍶" },
  { id: "coca-cola", name: "Coca-Cola", wiki: "Coca-Cola", category: "drinks", emoji: "🥤" },
  { id: "beer", name: "Beer", wiki: "Beer", category: "drinks", emoji: "🍺" },
  { id: "wine", name: "Wine", wiki: "Wine", category: "drinks", emoji: "🍷" },
  { id: "tea", name: "Tea", wiki: "Tea", category: "drinks", emoji: "🍵" },
  { id: "old-fashioned", name: "Old Fashioned", wiki: "Old_fashioned_(cocktail)", category: "drinks", emoji: "🥃" },
  { id: "martini", name: "Martini", wiki: "Martini_(cocktail)", category: "drinks", emoji: "🍸" },
  { id: "margarita", name: "Margarita", wiki: "Margarita", category: "drinks", emoji: "🍹" },
  { id: "cortado", name: "Cortado", wiki: "Cortado", category: "drinks", emoji: "☕" },
  { id: "flat-white", name: "Flat white", wiki: "Flat_white", category: "drinks", emoji: "☕" },
  { id: "sake", name: "Sake", wiki: "Sake", category: "drinks", emoji: "🍶" },
  { id: "chartreuse", name: "Chartreuse", wiki: "Chartreuse_(liqueur)", category: "drinks", emoji: "💚" },
  { id: "fernet-branca", name: "Fernet-Branca", wiki: "Fernet-Branca", category: "drinks", emoji: "🥃" },
  { id: "amaro", name: "Amaro", wiki: "Amaro_(liqueur)", category: "drinks", emoji: "🥃" },
  { id: "pisco", name: "Pisco", wiki: "Pisco", category: "drinks", emoji: "🇵🇪" },

  // --- brands ---
  { id: "starbucks", name: "Starbucks", wiki: "Starbucks", category: "brands", emoji: "☕" },
  { id: "blue-bottle", name: "Blue Bottle Coffee", wiki: "Blue_Bottle_Coffee", category: "brands", emoji: "☕" },
  { id: "stumptown", name: "Stumptown Coffee Roasters", wiki: "Stumptown_Coffee_Roasters", category: "brands", emoji: "☕" },
  { id: "patagonia", name: "Patagonia (clothing)", wiki: "Patagonia,_Inc.", category: "brands", emoji: "🧥" },
  { id: "supreme", name: "Supreme (brand)", wiki: "Supreme_(brand)", category: "brands", emoji: "🧢" },
  { id: "carhartt", name: "Carhartt", wiki: "Carhartt", category: "brands", emoji: "🧥" },
  { id: "moleskine", name: "Moleskine", wiki: "Moleskine", category: "brands", emoji: "📓" },
  { id: "leica", name: "Leica Camera", wiki: "Leica_Camera", category: "brands", emoji: "📷" },
  { id: "muji", name: "Muji", wiki: "Muji", category: "brands", emoji: "📦" },
  { id: "ikea", name: "IKEA", wiki: "IKEA", category: "brands", emoji: "🪑" },
  { id: "nike", name: "Nike, Inc.", wiki: "Nike,_Inc.", category: "brands", emoji: "✔️" },
  { id: "apple", name: "Apple Inc.", wiki: "Apple_Inc.", category: "brands", emoji: "🍎" },
  { id: "amazon", name: "Amazon", wiki: "Amazon_(company)", category: "brands", emoji: "📦" },
  { id: "target", name: "Target", wiki: "Target_Corporation", category: "brands", emoji: "🎯" },
  { id: "walmart", name: "Walmart", wiki: "Walmart", category: "brands", emoji: "🛒" },
  { id: "mcdonalds", name: "McDonald's", wiki: "McDonald%27s", category: "brands", emoji: "🍟" },
  { id: "aesop", name: "Aesop", wiki: "Aesop_(brand)", category: "brands", emoji: "🧴" },
  { id: "glossier", name: "Glossier", wiki: "Glossier", category: "brands", emoji: "💄" },
  { id: "goop", name: "Goop", wiki: "Goop_(company)", category: "brands", emoji: "✨" },
  { id: "stussy", name: "Stüssy", wiki: "St%C3%BCssy", category: "brands", emoji: "👕" },
  { id: "apc", name: "A.P.C.", wiki: "A.P.C.", category: "brands", emoji: "👖" },
  { id: "comme-des-garcons", name: "Comme des Garçons", wiki: "Comme_des_Gar%C3%A7ons", category: "brands", emoji: "👗" },
  { id: "issey-miyake", name: "Issey Miyake", wiki: "Issey_Miyake", category: "brands", emoji: "👘" },
  { id: "ace-hotel", name: "Ace Hotel", wiki: "Ace_Hotel", category: "brands", emoji: "🏨" },
  { id: "equinox", name: "Equinox Group", wiki: "Equinox_Group", category: "brands", emoji: "🏋️" },
  { id: "erewhon", name: "Erewhon", wiki: "Erewhon_Market", category: "brands", emoji: "🥗" },

  // --- hobbies ---
  { id: "knitting", name: "Knitting", wiki: "Knitting", category: "hobbies", emoji: "🧶" },
  { id: "bouldering", name: "Bouldering", wiki: "Bouldering", category: "hobbies", emoji: "🧗" },
  { id: "pottery", name: "Pottery", wiki: "Pottery", category: "hobbies", emoji: "🏺" },
  { id: "birdwatching", name: "Birdwatching", wiki: "Birdwatching", category: "hobbies", emoji: "🦜" },
  { id: "running", name: "Running", wiki: "Running", category: "hobbies", emoji: "🏃" },
  { id: "yoga", name: "Yoga", wiki: "Yoga", category: "hobbies", emoji: "🧘" },
  { id: "pickleball", name: "Pickleball", wiki: "Pickleball", category: "hobbies", emoji: "🏓" },
  { id: "disc-golf", name: "Disc golf", wiki: "Disc_golf", category: "hobbies", emoji: "🥏" },
  { id: "kintsugi", name: "Kintsugi", wiki: "Kintsugi", category: "hobbies", emoji: "🏺" },
  { id: "bonsai", name: "Bonsai", wiki: "Bonsai", category: "hobbies", emoji: "🌳" },
  { id: "golf", name: "Golf", wiki: "Golf", category: "hobbies", emoji: "⛳" },
  { id: "fishing", name: "Fishing", wiki: "Fishing", category: "hobbies", emoji: "🎣" },
  { id: "gardening", name: "Gardening", wiki: "Gardening", category: "hobbies", emoji: "🌻" },
  { id: "hiking", name: "Hiking", wiki: "Hiking", category: "hobbies", emoji: "🥾" },
  { id: "photography", name: "Photography", wiki: "Photography", category: "hobbies", emoji: "📷" },
  { id: "skateboarding", name: "Skateboarding", wiki: "Skateboarding", category: "hobbies", emoji: "🛹" },
  { id: "surfing", name: "Surfing", wiki: "Surfing", category: "hobbies", emoji: "🏄" },
  { id: "foraging", name: "Foraging", wiki: "Foraging", category: "hobbies", emoji: "🍄" },
  { id: "fermentation", name: "Fermentation in food processing", wiki: "Fermentation_in_food_processing", category: "hobbies", emoji: "🫙" },
  { id: "calligraphy", name: "Calligraphy", wiki: "Calligraphy", category: "hobbies", emoji: "🖋️" },
  { id: "embroidery", name: "Embroidery", wiki: "Embroidery", category: "hobbies", emoji: "🧵" },
  { id: "woodworking", name: "Woodworking", wiki: "Woodworking", category: "hobbies", emoji: "🪵" },
  { id: "fly-fishing", name: "Fly fishing", wiki: "Fly_fishing", category: "hobbies", emoji: "🎣" },
  { id: "bikepacking", name: "Bikepacking", wiki: "Bikepacking", category: "hobbies", emoji: "🚴" },
  { id: "vinyl-collecting", name: "Record collecting", wiki: "Record_collecting", category: "hobbies", emoji: "💿" },

  // --- tech ---
  { id: "iphone", name: "iPhone", wiki: "IPhone", category: "tech", emoji: "📱" },
  { id: "linux", name: "Linux", wiki: "Linux", category: "tech", emoji: "🐧" },
  { id: "arch-linux", name: "Arch Linux", wiki: "Arch_Linux", category: "tech", emoji: "🐧" },
  { id: "nixos", name: "NixOS", wiki: "NixOS", category: "tech", emoji: "❄️" },
  { id: "rust-lang", name: "Rust (programming language)", wiki: "Rust_(programming_language)", category: "tech", emoji: "🦀" },
  { id: "javascript", name: "JavaScript", wiki: "JavaScript", category: "tech", emoji: "🟨" },
  { id: "haskell", name: "Haskell", wiki: "Haskell", category: "tech", emoji: "λ" },
  { id: "vim", name: "Vim (text editor)", wiki: "Vim_(text_editor)", category: "tech", emoji: "📝" },
  { id: "emacs", name: "Emacs", wiki: "Emacs", category: "tech", emoji: "📝" },
  { id: "chatgpt", name: "ChatGPT", wiki: "ChatGPT", category: "tech", emoji: "🤖" },
  { id: "windows", name: "Microsoft Windows", wiki: "Microsoft_Windows", category: "tech", emoji: "🪟" },
  { id: "android", name: "Android (operating system)", wiki: "Android_(operating_system)", category: "tech", emoji: "🤖" },
  { id: "macos", name: "macOS", wiki: "MacOS", category: "tech", emoji: "💻" },
  { id: "chrome", name: "Google Chrome", wiki: "Google_Chrome", category: "tech", emoji: "🌐" },
  { id: "photoshop", name: "Adobe Photoshop", wiki: "Adobe_Photoshop", category: "tech", emoji: "🎨" },
  { id: "slack", name: "Slack", wiki: "Slack_(software)", category: "tech", emoji: "💬" },
  { id: "zoom", name: "Zoom", wiki: "Zoom_(software)", category: "tech", emoji: "📹" },
  { id: "elixir", name: "Elixir (programming language)", wiki: "Elixir_(programming_language)", category: "tech", emoji: "💧" },
  { id: "ocaml", name: "OCaml", wiki: "OCaml", category: "tech", emoji: "🐫" },
  { id: "zig", name: "Zig (programming language)", wiki: "Zig_(programming_language)", category: "tech", emoji: "⚡" },
  { id: "neovim", name: "Neovim", wiki: "Neovim", category: "tech", emoji: "📝" },
  { id: "tmux", name: "Tmux", wiki: "Tmux", category: "tech", emoji: "🖥️" },
  { id: "freebsd", name: "FreeBSD", wiki: "FreeBSD", category: "tech", emoji: "😈" },
  { id: "clojure", name: "Clojure", wiki: "Clojure", category: "tech", emoji: "🌀" },
  { id: "erlang", name: "Erlang (programming language)", wiki: "Erlang_(programming_language)", category: "tech", emoji: "📞" },
  { id: "apl", name: "APL (programming language)", wiki: "APL_(programming_language)", category: "tech", emoji: "🔤" },

  // --- animals ---
  { id: "golden-retriever", name: "Golden Retriever", wiki: "Golden_Retriever", category: "animals", emoji: "🐕" },
  { id: "shiba-inu", name: "Shiba Inu", wiki: "Shiba_Inu", category: "animals", emoji: "🐕" },
  { id: "bernedoodle", name: "Bernedoodle", wiki: "Bernedoodle", category: "animals", emoji: "🐕" },
  { id: "axolotl", name: "Axolotl", wiki: "Axolotl", category: "animals", emoji: "🦎" },
  { id: "capybara", name: "Capybara", wiki: "Capybara", category: "animals", emoji: "🐹" },
  { id: "octopus", name: "Octopus", wiki: "Octopus", category: "animals", emoji: "🐙" },
  { id: "ragdoll-cat", name: "Ragdoll", wiki: "Ragdoll", category: "animals", emoji: "🐈" },
  { id: "tardigrade", name: "Tardigrade", wiki: "Tardigrade", category: "animals", emoji: "🦠" },
  { id: "cat", name: "Cat", wiki: "Cat", category: "animals", emoji: "🐈" },
  { id: "dog", name: "Dog", wiki: "Dog", category: "animals", emoji: "🐕" },
  { id: "horse", name: "Horse", wiki: "Horse", category: "animals", emoji: "🐎" },
  { id: "lion", name: "Lion", wiki: "Lion", category: "animals", emoji: "🦁" },
  { id: "tiger", name: "Tiger", wiki: "Tiger", category: "animals", emoji: "🐅" },
  { id: "elephant", name: "Elephant", wiki: "Elephant", category: "animals", emoji: "🐘" },
  { id: "dolphin", name: "Dolphin", wiki: "Dolphin", category: "animals", emoji: "🐬" },
  { id: "fox", name: "Fox", wiki: "Fox", category: "animals", emoji: "🦊" },
  { id: "panda", name: "Giant panda", wiki: "Giant_panda", category: "animals", emoji: "🐼" },
  { id: "koala", name: "Koala", wiki: "Koala", category: "animals", emoji: "🐨" },
  { id: "penguin", name: "Penguin", wiki: "Penguin", category: "animals", emoji: "🐧" },
  { id: "corgi", name: "Pembroke Welsh Corgi", wiki: "Pembroke_Welsh_Corgi", category: "animals", emoji: "🐕" },
  { id: "dachshund", name: "Dachshund", wiki: "Dachshund", category: "animals", emoji: "🐕" },
  { id: "sphynx-cat", name: "Sphynx cat", wiki: "Sphynx_cat", category: "animals", emoji: "🐈" },
  { id: "maine-coon", name: "Maine Coon", wiki: "Maine_Coon", category: "animals", emoji: "🐈" },
  { id: "hedgehog", name: "Hedgehog", wiki: "Hedgehog", category: "animals", emoji: "🦔" },
  { id: "pangolin", name: "Pangolin", wiki: "Pangolin", category: "animals", emoji: "🦔" },
  { id: "narwhal", name: "Narwhal", wiki: "Narwhal", category: "animals", emoji: "🦄" },
  { id: "quokka", name: "Quokka", wiki: "Quokka", category: "animals", emoji: "🐹" },
  { id: "kakapo", name: "Kākāpō", wiki: "K%C4%81k%C4%81p%C5%8D", category: "animals", emoji: "🦜" },
  { id: "mantis-shrimp", name: "Mantis shrimp", wiki: "Mantis_shrimp", category: "animals", emoji: "🦐" },
];

export function itemsByCategory(category: Category | "mixed"): Item[] {
  if (category === "mixed") return ITEMS;
  return ITEMS.filter((i) => i.category === category);
}

export const CATEGORIES: { id: Category | "mixed"; label: string; emoji: string }[] = [
  { id: "mixed", label: "Mixed Bag", emoji: "🎲" },
  { id: "music", label: "Music", emoji: "🎸" },
  { id: "food", label: "Food", emoji: "🍕" },
  { id: "drinks", label: "Drinks", emoji: "☕" },
  { id: "cities", label: "Cities", emoji: "🏙️" },
  { id: "movies", label: "Movies", emoji: "🎬" },
  { id: "tv", label: "TV Shows", emoji: "📺" },
  { id: "books", label: "Books", emoji: "📚" },
  { id: "brands", label: "Brands", emoji: "🛍️" },
  { id: "hobbies", label: "Hobbies", emoji: "🧶" },
  { id: "tech", label: "Tech", emoji: "💻" },
  { id: "animals", label: "Animals", emoji: "🐙" },
];
